# Generated by Django 6.0.3 on 2026-06-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facture_avoir", "0002_normalize_index_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factureavoir",
            name="numero_avoir",
            field=models.CharField(
                help_text="Format ex: AV001/26",
                max_length=20,
                verbose_name="Numéro de la facture d'avoir",
            ),
        ),
    ]
