# Generated by Django 6.0.3 on 2026-06-18 11:43

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0015_article_article_company_archived_idx"),
        ("client", "0013_alter_client_company"),
        ("company", "0010_company_uses_foreign_currency"),
        ("facture_avoir", "0003_alter_factureavoir_numero_avoir"),
        ("facture_client", "0019_factureclient_date_echeance_and_more"),
        ("parameter", "0010_add_company_to_parameters"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalFactureAvoir",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "remarque",
                    models.TextField(
                        blank=True,
                        help_text="Remarque ou note supplémentaire pour le document",
                        null=True,
                        verbose_name="Remarque",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("Brouillon", "Brouillon"),
                            ("Envoyé", "Envoyé"),
                            ("Accepté", "Accepté"),
                            ("Refusé", "Refusé"),
                            ("Annulé", "Annulé"),
                            ("Expiré", "Expiré"),
                        ],
                        db_index=True,
                        default="Brouillon",
                        help_text="Statut du document (ex: Brouillon, Envoyé)",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "total_ht",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        help_text="Somme des totaux des lignes avant TVA",
                        max_digits=10,
                        verbose_name="Total HT",
                    ),
                ),
                (
                    "total_tva",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        help_text="Montant total de la TVA (calculé sur le HT après remise globale)",
                        max_digits=10,
                        verbose_name="Total TVA",
                    ),
                ),
                (
                    "total_ttc",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        help_text="Total TTC final (HT après remise + TVA sur HT après remise)",
                        max_digits=10,
                        verbose_name="Total TTC",
                    ),
                ),
                (
                    "remise_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("Pourcentage", "Pourcentage"),
                            ("Fixe", "Fixe"),
                        ],
                        default="",
                        help_text="Type de remise appliquée : 'Pourcentage' ou 'Fixe'",
                        max_length=12,
                        null=True,
                        verbose_name="Type de remise",
                    ),
                ),
                (
                    "remise",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Valeur de la remise appliquée",
                        max_digits=10,
                        verbose_name="Valeur remise",
                    ),
                ),
                (
                    "total_ttc_apres_remise",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        help_text="Total TTC après application de la remise (identique à total_ttc)",
                        max_digits=10,
                        verbose_name="Total TTC après remise",
                    ),
                ),
                (
                    "devise",
                    models.CharField(
                        choices=[
                            ("MAD", "MAD – Dirham Marocain"),
                            ("EUR", "EUR – Euro"),
                            ("USD", "USD – Dollar Américain"),
                        ],
                        db_index=True,
                        default="MAD",
                        help_text="Devise utilisée pour ce document (héritée du premier article ajouté)",
                        max_length=3,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Horodatage de la création du document",
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Horodatage de la dernière modification du document",
                        verbose_name="Date de mise à jour",
                    ),
                ),
                (
                    "numero_avoir",
                    models.CharField(
                        help_text="Format ex: AV001/26",
                        max_length=20,
                        verbose_name="Numéro de la facture d'avoir",
                    ),
                ),
                (
                    "date_avoir",
                    models.DateField(
                        db_index=True,
                        help_text="Date d'émission de la facture d'avoir",
                        verbose_name="Date de l'avoir",
                    ),
                ),
                (
                    "motif_avoir",
                    models.CharField(
                        choices=[
                            ("retour_marchandise", "Retour marchandise"),
                            ("erreur_facturation", "Erreur de facturation"),
                            ("remise", "Remise"),
                            ("annulation", "Annulation"),
                            ("autre", "Autre"),
                        ],
                        help_text="Motif obligatoire de la facture d'avoir",
                        max_length=30,
                        verbose_name="Motif de l'avoir",
                    ),
                ),
                (
                    "numero_bon_commande_client",
                    models.CharField(
                        blank=True,
                        help_text="Référence optionnelle pour les avoirs libres",
                        max_length=50,
                        null=True,
                        verbose_name="Référence client",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Client associé au document",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="client.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Société propriétaire de la facture d'avoir",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="company.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Utilisateur ayant créé le document",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par l'utilisateur",
                    ),
                ),
                (
                    "facture_origine",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Facture client créditée par cet avoir",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="facture_client.factureclient",
                        verbose_name="Facture d'origine",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mode_paiement",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Mode de paiement préféré pour le document",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="parameter.modepaiement",
                        verbose_name="Mode de paiement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique Facture d'avoir",
                "verbose_name_plural": "Historiques Factures d'avoir",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalFactureAvoirLine",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "prix_achat",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prix d'achat unitaire (ex: en MAD)",
                        max_digits=10,
                        verbose_name="Prix d'achat",
                    ),
                ),
                (
                    "devise_prix_achat",
                    models.CharField(
                        choices=[
                            ("MAD", "MAD – Dirham Marocain"),
                            ("EUR", "EUR – Euro"),
                            ("USD", "USD – Dollar Américain"),
                        ],
                        default="MAD",
                        help_text="Devise utilisée pour le prix d'achat",
                        max_length=3,
                        verbose_name="Devise prix d'achat",
                    ),
                ),
                (
                    "prix_vente",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prix de vente unitaire (ex: en MAD)",
                        max_digits=10,
                        verbose_name="Prix de vente",
                    ),
                ),
                (
                    "devise_prix_vente",
                    models.CharField(
                        choices=[
                            ("MAD", "MAD – Dirham Marocain"),
                            ("EUR", "EUR – Euro"),
                            ("USD", "USD – Dollar Américain"),
                        ],
                        default="MAD",
                        help_text="Devise utilisée pour le prix de vente",
                        max_length=3,
                        verbose_name="Devise prix de vente",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="Quantité (ex: 15,35)",
                        max_digits=10,
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "remise_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("Pourcentage", "Pourcentage"),
                            ("Fixe", "Fixe"),
                        ],
                        default="",
                        help_text="Type de remise appliquée : 'Pourcentage' ou 'Fixe'",
                        max_length=12,
                        null=True,
                        verbose_name="Type de remise",
                    ),
                ),
                (
                    "remise",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Valeur de la remise appliquée",
                        max_digits=10,
                        verbose_name="Valeur remise",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Article associé à cette ligne d'avoir",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="article.article",
                        verbose_name="Article",
                    ),
                ),
                (
                    "facture_avoir",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Facture d'avoir associée à cette ligne",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="facture_avoir.factureavoir",
                        verbose_name="Facture d'avoir",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique Ligne de facture d'avoir",
                "verbose_name_plural": "Historiques Lignes de factures d'avoir",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
