# Generated by Django 6.0.3 on 2026-08-18 10:49

from django.db import migrations, models


def backfill_supplier_from_origin(apps, schema_editor):
    FactureAvoir = apps.get_model("facture_avoir", "FactureAvoir")
    FactureClient = apps.get_model("facture_client", "FactureClient")

    for credit_note in FactureAvoir.objects.exclude(facture_origine_id=None).iterator():
        origin = (
            FactureClient.objects.filter(pk=credit_note.facture_origine_id)
            .values("fournisseur", "fournisseur_email")
            .first()
        )
        if not origin:
            continue
        updates = {}
        if not credit_note.fournisseur and origin["fournisseur"]:
            updates["fournisseur"] = origin["fournisseur"]
        if not credit_note.fournisseur_email and origin["fournisseur_email"]:
            updates["fournisseur_email"] = origin["fournisseur_email"]
        if updates:
            FactureAvoir.objects.filter(pk=credit_note.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ("facture_avoir", "0004_historicalfactureavoir_historicalfactureavoirline"),
        ("facture_client", "0022_factureclient_fournisseur_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="factureavoir",
            name="fournisseur",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Fournisseur interne repris lors des conversions",
                max_length=255,
                verbose_name="Fournisseur",
            ),
        ),
        migrations.AddField(
            model_name="factureavoir",
            name="fournisseur_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Adresse interne reprise lors des conversions",
                max_length=254,
                verbose_name="E-mail fournisseur",
            ),
        ),
        migrations.AddField(
            model_name="historicalfactureavoir",
            name="fournisseur",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Fournisseur interne repris lors des conversions",
                max_length=255,
                verbose_name="Fournisseur",
            ),
        ),
        migrations.AddField(
            model_name="historicalfactureavoir",
            name="fournisseur_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Adresse interne reprise lors des conversions",
                max_length=254,
                verbose_name="E-mail fournisseur",
            ),
        ),
        migrations.RunPython(backfill_supplier_from_origin, migrations.RunPython.noop),
    ]
