# Generated by Django 6.0 on 2026-01-02 12:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("facture_client", "0004_alter_factureclient_total_ht_and_more"),
        ("parameter", "0005_livrepar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reglement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Libellé"
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant du règlement (en MAD)",
                        max_digits=10,
                        verbose_name="Montant",
                    ),
                ),
                (
                    "date_reglement",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Date de règlement",
                    ),
                ),
                (
                    "date_echeance",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Date d'échéance",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("Valide", "Valide"), ("Annulé", "Annulé")],
                        default="Valide",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "facture_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reglements",
                        to="facture_client.factureclient",
                        verbose_name="Facture Client",
                    ),
                ),
                (
                    "mode_reglement",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="parameter.modereglement",
                        verbose_name="Mode de règlement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Règlement",
                "verbose_name_plural": "Règlements",
                "ordering": ("-date_created",),
            },
        ),
    ]
