# Generated by Django 6.0.1 on 2026-01-13 09:18

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facture_client", "0005_historicalfactureclient_historicalfactureclientline"),
        ("parameter", "0005_livrepar"),
        ("reglement", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="reglement",
            name="mode_reglement",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="parameter.modepaiement",
                verbose_name="Mode de règlement",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalReglement",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Libellé"
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant du règlement (en MAD)",
                        max_digits=10,
                        verbose_name="Montant",
                    ),
                ),
                (
                    "date_reglement",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Date de règlement",
                    ),
                ),
                (
                    "date_echeance",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Date d'échéance",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("Valide", "Valide"), ("Annulé", "Annulé")],
                        default="Valide",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Date de mise à jour"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "facture_client",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="facture_client.factureclient",
                        verbose_name="Facture Client",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mode_reglement",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="parameter.modepaiement",
                        verbose_name="Mode de règlement",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Règlement",
                "verbose_name_plural": "historical Règlements",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
