# Generated by Django 6.0.1 on 2026-01-21 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facture_client", "0006_alter_factureclient_client_and_more"),
        ("reglement", "0002_alter_reglement_mode_reglement_historicalreglement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reglement",
            name="facture_client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reglements",
                to="facture_client.factureclient",
                verbose_name="Facture Client",
            ),
        ),
    ]
