# Generated by Django 6.0 on 2026-01-26 11:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facture_client", "0007_alter_factureclient_client_and_more"),
        ("parameter", "0008_alter_categorie_nom_alter_emplacement_nom_and_more"),
        ("reglement", "0003_alter_reglement_facture_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalreglement",
            name="date_created",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Horodatage de la création du règlement",
                verbose_name="Date de création",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreglement",
            name="date_echeance",
            field=models.DateField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="Date d'échéance du paiement",
                verbose_name="Date d'échéance",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreglement",
            name="date_reglement",
            field=models.DateField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="Date à laquelle le règlement a été effectué",
                verbose_name="Date de règlement",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreglement",
            name="date_updated",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Horodatage de la dernière modification du règlement",
                verbose_name="Date de mise à jour",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreglement",
            name="facture_client",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Facture client associée au règlement",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="facture_client.factureclient",
                verbose_name="Facture Client",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreglement",
            name="libelle",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Libellé ou description du règlement",
                max_length=255,
                verbose_name="Libellé",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreglement",
            name="mode_reglement",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Mode de paiement utilisé pour ce règlement",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="parameter.modepaiement",
                verbose_name="Mode de règlement",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreglement",
            name="statut",
            field=models.CharField(
                choices=[("Valide", "Valide"), ("Annulé", "Annulé")],
                default="Valide",
                help_text="Statut du règlement (ex: Valide, Annulé)",
                max_length=10,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="reglement",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Horodatage de la création du règlement",
                verbose_name="Date de création",
            ),
        ),
        migrations.AlterField(
            model_name="reglement",
            name="date_echeance",
            field=models.DateField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="Date d'échéance du paiement",
                verbose_name="Date d'échéance",
            ),
        ),
        migrations.AlterField(
            model_name="reglement",
            name="date_reglement",
            field=models.DateField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="Date à laquelle le règlement a été effectué",
                verbose_name="Date de règlement",
            ),
        ),
        migrations.AlterField(
            model_name="reglement",
            name="date_updated",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Horodatage de la dernière modification du règlement",
                verbose_name="Date de mise à jour",
            ),
        ),
        migrations.AlterField(
            model_name="reglement",
            name="facture_client",
            field=models.ForeignKey(
                help_text="Facture client associée au règlement",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reglements",
                to="facture_client.factureclient",
                verbose_name="Facture Client",
            ),
        ),
        migrations.AlterField(
            model_name="reglement",
            name="libelle",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Libellé ou description du règlement",
                max_length=255,
                verbose_name="Libellé",
            ),
        ),
        migrations.AlterField(
            model_name="reglement",
            name="mode_reglement",
            field=models.ForeignKey(
                help_text="Mode de paiement utilisé pour ce règlement",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="parameter.modepaiement",
                verbose_name="Mode de règlement",
            ),
        ),
        migrations.AlterField(
            model_name="reglement",
            name="statut",
            field=models.CharField(
                choices=[("Valide", "Valide"), ("Annulé", "Annulé")],
                default="Valide",
                help_text="Statut du règlement (ex: Valide, Annulé)",
                max_length=10,
                verbose_name="Statut",
            ),
        ),
    ]
