# Generated by Django 6.0 on 2026-01-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reglement", "0004_alter_historicalreglement_date_created_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalreglement",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "Historique Règlement",
                "verbose_name_plural": "Historiques Règlements",
            },
        ),
    ]
