# Generated by Django 6.0 on 2026-02-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reglement", "0005_alter_historicalreglement_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalreglement",
            name="montant",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Montant du règlement (devise héritée de la facture client)",
                max_digits=10,
                verbose_name="Montant",
            ),
        ),
        migrations.AlterField(
            model_name="reglement",
            name="montant",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Montant du règlement (devise héritée de la facture client)",
                max_digits=10,
                verbose_name="Montant",
            ),
        ),
    ]
