# Generated by Django 6.0 on 2026-02-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reglement", "0006_alter_historicalreglement_montant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalreglement",
            name="statut",
            field=models.CharField(
                choices=[("Valide", "Valide"), ("Annulé", "Annulé")],
                db_index=True,
                default="Valide",
                help_text="Statut du règlement (ex: Valide, Annulé)",
                max_length=10,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="reglement",
            name="statut",
            field=models.CharField(
                choices=[("Valide", "Valide"), ("Annulé", "Annulé")],
                db_index=True,
                default="Valide",
                help_text="Statut du règlement (ex: Valide, Annulé)",
                max_length=10,
                verbose_name="Statut",
            ),
        ),
    ]
