# Generated by Django 6.0.2 on 2026-02-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "facture_client",
            "0015_factureclient_facture_cli_company_1b551e_idx_and_more",
        ),
        ("parameter", "0010_add_company_to_parameters"),
        ("reglement", "0007_alter_historicalreglement_statut_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="reglement",
            index=models.Index(
                fields=["facture_client", "statut"],
                name="reglement_r_facture_e4fbda_idx",
            ),
        ),
    ]
