# Generated by Django 6.0.3 on 2026-06-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reglement", "0008_reglement_reglement_r_facture_e4fbda_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreglement",
            name="observations",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Observations optionnelles concernant le règlement",
                verbose_name="Observations",
            ),
        ),
        migrations.AddField(
            model_name="reglement",
            name="observations",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Observations optionnelles concernant le règlement",
                verbose_name="Observations",
            ),
        ),
    ]
