# Generated by Django 5.2.8 on 2025-11-14 11:52

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="avatar_thumbnail",
        ),
        migrations.AddField(
            model_name="customuser",
            name="avatar_cropped",
            field=models.ImageField(
                blank=True,
                default=None,
                max_length=1000,
                null=True,
                upload_to=account.models.get_avatar_path,
                verbose_name="Avatar cropped",
            ),
        ),
    ]
