# Generated by Django 5.2.7 on 2025-10-24 14:27

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='activation_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='task_id_activation',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=account.models.get_avatar_path, verbose_name='User Avatar'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar_thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=account.models.get_avatar_path, verbose_name='User Avatar'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Unset'), ('H', 'Homme'), ('F', 'Femme')], default='', max_length=1, null=True),
        ),
    ]
