# Generated by Django 5.2.7 on 2025-10-24 15:07

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_activation_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar_thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=account.models.get_avatar_path, verbose_name='User Avatar thumbnail'),
        ),
    ]
