# Generated by Django 5.2.8 on 2025-11-27 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_customuser_avatar_thumbnail_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("company", "0004_alter_company_civilite_responsable_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="date_joined",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="date joined",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[("", "Unset"), ("H", "Homme"), ("F", "Femme")],
                default="",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Designates whether this user should be treated as active. "
                "Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password_reset_code",
            field=models.CharField(
                blank=True, db_index=True, null=True, verbose_name="Password Reset Code"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="task_id_password_reset",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=40,
                null=True,
                verbose_name="Task ID password reset",
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["user", "role"], name="accounts_me_user_id_be7be9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["company", "role"], name="accounts_me_company_fe7c86_idx"
            ),
        ),
    ]
