# Generated by Django 5.2.8 on 2025-11-27 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_alter_customuser_date_joined_alter_customuser_gender_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ("-date_joined",),
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
