# Generated by Django 5.2.7 on 2025-10-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_avatar_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password_reset_code',
            field=models.CharField(blank=True, null=True, verbose_name='Password Reset Code'),
        ),
    ]
