# Generated by Django 6.0 on 2025-12-18 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_options"),
        ("company", "0005_alter_company_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="company.company",
                verbose_name="Company",
            ),
        ),
    ]
