# Generated by Django 6.0.1 on 2026-01-26 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_historicalcustomuser_historicalmembership"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="is_admin",
        ),
    ]
