# Generated by Django 6.0 on 2026-01-26 11:11

import account.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_remove_role_is_admin"),
        ("company", "0008_alter_company_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ("-date_joined",),
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcustomuser",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Utilisateur",
                "verbose_name_plural": "historical Utilisateurs",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalmembership",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Membre",
                "verbose_name_plural": "historical Membres",
            },
        ),
        migrations.AlterModelOptions(
            name="membership",
            options={
                "ordering": ("role",),
                "verbose_name": "Membre",
                "verbose_name_plural": "Membres",
            },
        ),
        migrations.AlterModelOptions(
            name="role",
            options={
                "ordering": ("name",),
                "verbose_name": "Rôle",
                "verbose_name_plural": "Rôles",
            },
        ),
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default=None,
                help_text="Image de profil de l'utilisateur (format recommandé: WebP)",
                null=True,
                upload_to=account.models.get_avatar_path,
                verbose_name="Photo de profil",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="avatar_cropped",
            field=models.ImageField(
                blank=True,
                default=None,
                help_text="Version recadrée de la photo de profil",
                max_length=1000,
                null=True,
                upload_to=account.models.get_avatar_path,
                verbose_name="Photo de profil recadrée",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="date_joined",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="Horodatage de l'inscription de l'utilisateur",
                verbose_name="Date d'inscription",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="date_updated",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Horodatage de la dernière modification du compte",
                verbose_name="Date de modification",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                help_text="Adresse e‑mail de l'utilisateur",
                max_length=254,
                unique=True,
                verbose_name="Adresse e‑mail",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="Prénom de l'utilisateur",
                max_length=30,
                verbose_name="Prénom",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[("", "Unset"), ("H", "Homme"), ("F", "Femme")],
                default="",
                help_text="Sexe de l'utilisateur",
                max_length=1,
                verbose_name="Sexe",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Indique si ce compte doit être considéré comme actif.",
                verbose_name="Actif",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indique si l'utilisateur peut se connecter au panneau d'administration.",
                verbose_name="Statut personnel",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(
                blank=True,
                help_text="Nom de famille de l'utilisateur",
                max_length=30,
                verbose_name="Nom",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password_reset_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Code envoyé pour la réinitialisation du mot de passe",
                null=True,
                verbose_name="Mot de passe - Code de réinitialisation",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="task_id_password_reset",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                help_text="Identifiant de la tâche de réinitialisation du mot de passe",
                max_length=40,
                null=True,
                verbose_name="Mot de passe - Task ID de réinitialisation",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="avatar",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Image de profil de l'utilisateur (format recommandé: WebP)",
                max_length=100,
                null=True,
                verbose_name="Photo de profil",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="avatar_cropped",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Version recadrée de la photo de profil",
                max_length=1000,
                null=True,
                verbose_name="Photo de profil recadrée",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="date_joined",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="Horodatage de l'inscription de l'utilisateur",
                verbose_name="Date d'inscription",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="date_updated",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Horodatage de la dernière modification du compte",
                verbose_name="Date de modification",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="email",
            field=models.EmailField(
                db_index=True,
                help_text="Adresse e‑mail de l'utilisateur",
                max_length=254,
                verbose_name="Adresse e‑mail",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="Prénom de l'utilisateur",
                max_length=30,
                verbose_name="Prénom",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="gender",
            field=models.CharField(
                choices=[("", "Unset"), ("H", "Homme"), ("F", "Femme")],
                default="",
                help_text="Sexe de l'utilisateur",
                max_length=1,
                verbose_name="Sexe",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Indique si ce compte doit être considéré comme actif.",
                verbose_name="Actif",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="is_staff",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indique si l'utilisateur peut se connecter au panneau d'administration.",
                verbose_name="Statut personnel",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="last_name",
            field=models.CharField(
                blank=True,
                help_text="Nom de famille de l'utilisateur",
                max_length=30,
                verbose_name="Nom",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="password_reset_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Code envoyé pour la réinitialisation du mot de passe",
                null=True,
                verbose_name="Mot de passe - Code de réinitialisation",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="task_id_password_reset",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                help_text="Identifiant de la tâche de réinitialisation du mot de passe",
                max_length=40,
                null=True,
                verbose_name="Mot de passe - Task ID de réinitialisation",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="company",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Société à laquelle l'utilisateur est rattaché",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="company.company",
                verbose_name="Société",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="role",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Rôle assigné à l'utilisateur dans l'entreprise",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounts.role",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Utilisateur membre",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Société à laquelle l'utilisateur est rattaché",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="company.company",
                verbose_name="Société",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.ForeignKey(
                blank=True,
                help_text="Rôle assigné à l'utilisateur dans l'entreprise",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.role",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="user",
            field=models.ForeignKey(
                help_text="Utilisateur membre",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                help_text="Nom unique du rôle",
                max_length=150,
                unique=True,
                verbose_name="Nom rôle",
            ),
        ),
    ]
