# Generated by Django 6.0.1 on 2026-01-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="default_password_set",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indique si l'utilisateur utilise encore le mot de passe par défaut envoyé par e-mail",
                verbose_name="Mot de passe par défaut défini",
            ),
        ),
        migrations.AddField(
            model_name="historicalcustomuser",
            name="default_password_set",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indique si l'utilisateur utilise encore le mot de passe par défaut envoyé par e-mail",
                verbose_name="Mot de passe par défaut défini",
            ),
        ),
    ]
