# Generated by Django 6.0 on 2026-01-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_customuser_default_password_set_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalcustomuser",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "Historique Utilisateur",
                "verbose_name_plural": "Historiques Utilisateurs",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalmembership",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "Historique Membre",
                "verbose_name_plural": "Historiques Membres",
            },
        ),
    ]
