# Generated by Django 6.0 on 2026-02-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_historicalcustomuser_options_and_more"),
        ("company", "0010_company_uses_foreign_currency"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("user", "company"), name="unique_user_company_membership"
            ),
        ),
    ]
