# Generated by Django 6.0.2 on 2026-02-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_membership_unique_user_company_membership"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="password_reset_code_created_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Date et heure de création du code de réinitialisation (expire après 5 minutes)",
                null=True,
                verbose_name="Mot de passe - Date de création du code",
            ),
        ),
        migrations.AddField(
            model_name="historicalcustomuser",
            name="password_reset_code_created_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Date et heure de création du code de réinitialisation (expire après 5 minutes)",
                null=True,
                verbose_name="Mot de passe - Date de création du code",
            ),
        ),
    ]
