# Generated by Django 6.0.3 on 2026-06-18 10:52

from django.db import migrations, models


def allow_existing_caissiers_to_validate(apps, _schema_editor):
    Membership = apps.get_model("accounts", "Membership")
    Membership.objects.filter(role__name="Caissier").update(can_validate_factures=True)


def unset_existing_caissier_validation(apps, _schema_editor):
    Membership = apps.get_model("accounts", "Membership")
    Membership.objects.filter(role__name="Caissier").update(can_validate_factures=False)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_customuser_sso_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmembership",
            name="can_validate_factures",
            field=models.BooleanField(
                default=False,
                help_text="Autorise cet utilisateur à valider les factures client.",
                verbose_name="Autoriser la validation des factures",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="can_validate_factures",
            field=models.BooleanField(
                default=False,
                help_text="Autorise cet utilisateur à valider les factures client.",
                verbose_name="Autoriser la validation des factures",
            ),
        ),
        migrations.RunPython(
            allow_existing_caissiers_to_validate,
            unset_existing_caissier_validation,
        ),
    ]
