# Generated by Codex on 2026-06-26

from django.db import migrations, models


def allow_existing_caissiers_to_change_status(apps, _schema_editor):
    Membership = apps.get_model("accounts", "Membership")
    Membership.objects.filter(role__name="Caissier").update(
        can_change_document_status=True
    )


def unset_existing_caissier_status_permission(apps, _schema_editor):
    Membership = apps.get_model("accounts", "Membership")
    Membership.objects.filter(role__name="Caissier").update(
        can_change_document_status=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_historicalmembership_can_validate_factures_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmembership",
            name="can_change_document_status",
            field=models.BooleanField(
                default=False,
                help_text="Autorise cet utilisateur à modifier le statut des documents.",
                verbose_name="Autoriser le changement de statut des documents",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="can_change_document_status",
            field=models.BooleanField(
                default=False,
                help_text="Autorise cet utilisateur à modifier le statut des documents.",
                verbose_name="Autoriser le changement de statut des documents",
            ),
        ),
        migrations.RunPython(
            allow_existing_caissiers_to_change_status,
            unset_existing_caissier_status_permission,
        ),
    ]
