# Generated by Django 6.1.1 on 2026-09-10 15:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("article", "0016_article_stock_minimum_and_more"),
        ("company", "0011_company_stock_management_enabled_and_more"),
        ("facture_proforma", "0025_alter_factureproforma_fournisseur_and_more"),
        ("logistique", "0012_logisticsorderline_expected_emplacement_and_more"),
        ("parameter", "0010_add_company_to_parameters"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventorySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("validated", "Validé"),
                            ("cancelled", "Annulé"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=80)),
                ("note", models.TextField(blank=True, default="")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_validated", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_inventories",
                        to="company.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventories_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "emplacement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_inventories",
                        to="parameter.emplacement",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventories_validated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-date_created",),
            },
        ),
        migrations.CreateModel(
            name="StockBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "physical_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "reserved_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_balances",
                        to="article.article",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_balances",
                        to="company.company",
                    ),
                ),
                (
                    "emplacement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_balances",
                        to="parameter.emplacement",
                    ),
                ),
            ],
            options={
                "ordering": ("article__reference", "emplacement__nom"),
            },
        ),
        migrations.CreateModel(
            name="LowStockAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("first_detected_at", models.DateTimeField(auto_now_add=True)),
                ("last_notified_at", models.DateTimeField(blank=True, null=True)),
                ("recovered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "balance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="low_stock_alert",
                        to="stock.stockbalance",
                    ),
                ),
            ],
            options={
                "ordering": ("-first_detected_at",),
            },
        ),
        migrations.CreateModel(
            name="StockReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("validated", "Validée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=80)),
                ("note", models.TextField(blank=True, default="")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_validated", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_receipts",
                        to="company.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_receipts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "logistics_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_receipts",
                        to="logistique.logisticsorder",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_receipts_validated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-date_created",),
            },
        ),
        migrations.CreateModel(
            name="StockReceiptLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="article.article",
                    ),
                ),
                (
                    "emplacement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parameter.emplacement",
                    ),
                ),
                (
                    "logistics_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt_lines",
                        to="logistique.logisticsorderline",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="stock.stockreceipt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reserved_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "consumed_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "released_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("released", "Libérée"),
                            ("consumed", "Consommée"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "balance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="stock.stockbalance",
                    ),
                ),
                (
                    "proforma_line",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="facture_proforma.factureproformaline",
                    ),
                ),
            ],
            options={
                "ordering": ("-date_created",),
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("opening", "Stock initial"),
                            ("adjustment", "Ajustement"),
                            ("receipt", "Réception"),
                            ("delivery", "Livraison"),
                            ("inventory", "Inventaire"),
                            ("reversal", "Annulation"),
                        ],
                        max_length=16,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("balance_after", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "source_type",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("source_id", models.PositiveIntegerField(blank=True, null=True)),
                ("source_line_id", models.PositiveIntegerField(blank=True, null=True)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, max_length=120, null=True, unique=True
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "balance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="stock.stockbalance",
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="stock.stockmovement",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="stock.stockreservation",
                    ),
                ),
            ],
            options={
                "ordering": ("-date_created", "-id"),
            },
        ),
        migrations.CreateModel(
            name="InventoryLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expected_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "counted_quantity",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="article.article",
                    ),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="stock.inventorysession",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("inventory", "article"), name="unique_inventory_article"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="stockbalance",
            index=models.Index(
                fields=["company", "article"], name="stock_bal_company_article"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbalance",
            constraint=models.UniqueConstraint(
                fields=("company", "article", "emplacement"),
                name="unique_stock_balance",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbalance",
            constraint=models.CheckConstraint(
                condition=models.Q(("physical_quantity__gte", 0)),
                name="stock_physical_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbalance",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_quantity__gte", 0)),
                name="stock_reserved_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockreceiptline",
            constraint=models.UniqueConstraint(
                fields=("receipt", "logistics_line"),
                name="unique_receipt_logistics_line",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["balance", "date_created"], name="stock_move_balance_date"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["source_type", "source_id"], name="stock_move_source"
            ),
        ),
    ]
