# Generated by Django 6.1.1 on 2026-10-07 10:55

from datetime import timedelta
from django.db import migrations, models
from django.utils import timezone


def start_existing_holds(apps, schema_editor):
    # Existing reservations get a full seven-day notice period from rollout.
    apps.get_model("stock", "StockReservation").objects.using(
        schema_editor.connection.alias
    ).filter(status="active", expires_at__isnull=True).update(
        expires_at=timezone.now() + timedelta(days=7)
    )


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockreservation",
            name="expires_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="stockreservation",
            name="expiry_reminded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(start_existing_holds, migrations.RunPython.noop),
    ]
