# Generated by Django 5.2.8 on 2025-11-17 10:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0003_alter_company_cachet_alter_company_cachet_cropped_and_more"),
        ("parameter", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_client",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Code client"
                    ),
                ),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("PM", "personne morale"),
                            ("PP", "personne physique"),
                        ],
                        max_length=2,
                        verbose_name="Type de client",
                    ),
                ),
                (
                    "adresse",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Adresse"
                    ),
                ),
                (
                    "tel",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Tapez un numéro de téléphone valide",
                                regex="^\\+?\\d{7,15}$",
                            )
                        ],
                        verbose_name="Téléphone",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="E‑mail"
                    ),
                ),
                (
                    "delai_de_paiement",
                    models.PositiveIntegerField(
                        blank=True,
                        default=60,
                        null=True,
                        verbose_name="Délai de paiement",
                    ),
                ),
                (
                    "remarque",
                    models.TextField(blank=True, null=True, verbose_name="Remarque"),
                ),
                (
                    "raison_sociale",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Raison sociale",
                    ),
                ),
                (
                    "numero_du_compte",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Numéro du compte",
                    ),
                ),
                (
                    "ICE",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="ICE"
                    ),
                ),
                (
                    "registre_de_commerce",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Registre de commerce",
                    ),
                ),
                (
                    "identifiant_fiscal",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Identifiant fiscal",
                    ),
                ),
                (
                    "taxe_professionnelle",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Taxe professionnelle",
                    ),
                ),
                (
                    "CNSS",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="CNSS"
                    ),
                ),
                (
                    "fax",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Tapez un numéro de téléphone valide",
                                regex="^\\+?\\d{7,15}$",
                            )
                        ],
                        verbose_name="Fax",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Nom"
                    ),
                ),
                (
                    "prenom",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Prénom"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clients",
                        to="company.company",
                        verbose_name="Entreprise",
                    ),
                ),
                (
                    "ville",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="parameter.ville",
                        verbose_name="Ville",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
    ]
