# Generated by Django 5.2.8 on 2025-11-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_client_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="Archivé"),
        ),
    ]
