# Generated by Django 5.2.8 on 2025-11-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0003_client_archived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_type",
            field=models.CharField(
                choices=[("PM", "Personne morale"), ("PP", "Personne physique")],
                max_length=2,
                verbose_name="Type de client",
            ),
        ),
    ]
