# Generated by Django 5.2.8 on 2025-11-27 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0004_alter_client_client_type"),
        ("company", "0004_alter_company_civilite_responsable_and_more"),
        ("parameter", "0002_alter_ville_nom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="archived",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Archivé"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="date_created",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["company", "archived"], name="client_clie_company_cdb1d9_idx"
            ),
        ),
    ]
