# Generated by Django 5.2.8 on 2025-11-27 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0005_alter_client_archived_alter_client_date_created_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ("code_client",),
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
    ]
