# Generated by Django 5.2.8 on 2025-11-27 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0006_alter_client_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ("-date_created",),
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
    ]
