# Generated by Django 6.0 on 2026-01-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_client_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de modification'),
        ),
    ]
