# Generated by Django 6.0.1 on 2026-01-13 09:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0008_client_date_updated"),
        ("company", "0007_company_suspended_historicalcompany"),
        ("parameter", "0005_livrepar"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalClient",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "code_client",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Code client"
                    ),
                ),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("PM", "Personne morale"),
                            ("PP", "Personne physique"),
                        ],
                        max_length=2,
                        verbose_name="Type de client",
                    ),
                ),
                (
                    "adresse",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Adresse"
                    ),
                ),
                (
                    "tel",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Tapez un numéro de téléphone valide",
                                regex="^\\+?\\d{7,15}$",
                            )
                        ],
                        verbose_name="Téléphone",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="E‑mail"
                    ),
                ),
                (
                    "delai_de_paiement",
                    models.PositiveIntegerField(
                        blank=True,
                        default=60,
                        null=True,
                        verbose_name="Délai de paiement",
                    ),
                ),
                (
                    "remarque",
                    models.TextField(blank=True, null=True, verbose_name="Remarque"),
                ),
                (
                    "raison_sociale",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Raison sociale",
                    ),
                ),
                (
                    "numero_du_compte",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Numéro du compte",
                    ),
                ),
                (
                    "ICE",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="ICE"
                    ),
                ),
                (
                    "registre_de_commerce",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Registre de commerce",
                    ),
                ),
                (
                    "identifiant_fiscal",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Identifiant fiscal",
                    ),
                ),
                (
                    "taxe_professionnelle",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Taxe professionnelle",
                    ),
                ),
                (
                    "CNSS",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="CNSS"
                    ),
                ),
                (
                    "fax",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Tapez un numéro de téléphone valide",
                                regex="^\\+?\\d{7,15}$",
                            )
                        ],
                        verbose_name="Fax",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Nom"
                    ),
                ),
                (
                    "prenom",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Prénom"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        verbose_name="Date de modification",
                    ),
                ),
                (
                    "archived",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Archivé"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="company.company",
                        verbose_name="Entreprise",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ville",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="parameter.ville",
                        verbose_name="Ville",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Client",
                "verbose_name_plural": "historical Clients",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
