# Generated by Django 6.0 on 2026-01-26 11:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0009_historicalclient"),
        ("company", "0008_alter_company_options_and_more"),
        ("parameter", "0008_alter_categorie_nom_alter_emplacement_nom_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="CNSS",
            field=models.CharField(
                blank=True,
                help_text="Numéro CNSS",
                max_length=100,
                null=True,
                verbose_name="CNSS",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="ICE",
            field=models.CharField(
                blank=True,
                help_text="Identifiant Commun de l'Entreprise (ICE)",
                max_length=100,
                null=True,
                verbose_name="ICE",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="adresse",
            field=models.CharField(
                blank=True,
                help_text="Adresse postale du client",
                max_length=255,
                null=True,
                verbose_name="Adresse",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="archived",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indique si le client est archivé",
                verbose_name="Archivé",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="client_type",
            field=models.CharField(
                choices=[("PM", "Personne morale"), ("PP", "Personne physique")],
                help_text="Type : Personne morale (PM) ou physique (PP)",
                max_length=2,
                verbose_name="Type de client",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="code_client",
            field=models.CharField(
                help_text="Code unique identifiant le client",
                max_length=50,
                unique=True,
                verbose_name="Code client",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Entreprise associée au client (si personne morale)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clients",
                to="company.company",
                verbose_name="Entreprise",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="date_created",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="Horodatage de la création du client",
                verbose_name="Date de création",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="date_updated",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Horodatage de la dernière modification",
                verbose_name="Date de modification",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="delai_de_paiement",
            field=models.PositiveIntegerField(
                blank=True,
                default=60,
                help_text="Délai de paiement en jours",
                null=True,
                verbose_name="Délai de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Adresse e‑mail du client",
                max_length=254,
                null=True,
                verbose_name="E‑mail",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="fax",
            field=models.CharField(
                blank=True,
                help_text="Numéro de fax (optionnel)",
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Tapez un numéro de téléphone valide",
                        regex="^\\+?\\d{7,15}$",
                    )
                ],
                verbose_name="Fax",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="identifiant_fiscal",
            field=models.CharField(
                blank=True,
                help_text="Identifiant fiscal (IF)",
                max_length=100,
                null=True,
                verbose_name="Identifiant fiscal",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="nom",
            field=models.CharField(
                blank=True,
                help_text="Nom (pour personne physique)",
                max_length=100,
                null=True,
                verbose_name="Nom",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="numero_du_compte",
            field=models.CharField(
                blank=True,
                help_text="Numéro de compte bancaire du client",
                max_length=100,
                null=True,
                verbose_name="Numéro du compte",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="prenom",
            field=models.CharField(
                blank=True,
                help_text="Prénom (pour personne physique)",
                max_length=100,
                null=True,
                verbose_name="Prénom",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="raison_sociale",
            field=models.CharField(
                blank=True,
                help_text="Raison sociale pour les personnes morales",
                max_length=255,
                null=True,
                verbose_name="Raison sociale",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="registre_de_commerce",
            field=models.CharField(
                blank=True,
                help_text="Numéro du registre de commerce",
                max_length=100,
                null=True,
                verbose_name="Registre de commerce",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="remarque",
            field=models.TextField(
                blank=True,
                help_text="Remarque ou note concernant le client",
                null=True,
                verbose_name="Remarque",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="taxe_professionnelle",
            field=models.CharField(
                blank=True,
                help_text="Référence de la taxe professionnelle",
                max_length=100,
                null=True,
                verbose_name="Taxe professionnelle",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="tel",
            field=models.CharField(
                blank=True,
                help_text="Numéro de téléphone principal",
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Tapez un numéro de téléphone valide",
                        regex="^\\+?\\d{7,15}$",
                    )
                ],
                verbose_name="Téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="ville",
            field=models.ForeignKey(
                blank=True,
                help_text="Ville du client",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="parameter.ville",
                verbose_name="Ville",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="CNSS",
            field=models.CharField(
                blank=True,
                help_text="Numéro CNSS",
                max_length=100,
                null=True,
                verbose_name="CNSS",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="ICE",
            field=models.CharField(
                blank=True,
                help_text="Identifiant Commun de l'Entreprise (ICE)",
                max_length=100,
                null=True,
                verbose_name="ICE",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="adresse",
            field=models.CharField(
                blank=True,
                help_text="Adresse postale du client",
                max_length=255,
                null=True,
                verbose_name="Adresse",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="archived",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indique si le client est archivé",
                verbose_name="Archivé",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="client_type",
            field=models.CharField(
                choices=[("PM", "Personne morale"), ("PP", "Personne physique")],
                help_text="Type : Personne morale (PM) ou physique (PP)",
                max_length=2,
                verbose_name="Type de client",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="code_client",
            field=models.CharField(
                db_index=True,
                help_text="Code unique identifiant le client",
                max_length=50,
                verbose_name="Code client",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="company",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Entreprise associée au client (si personne morale)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="company.company",
                verbose_name="Entreprise",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="date_created",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="Horodatage de la création du client",
                verbose_name="Date de création",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="date_updated",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Horodatage de la dernière modification",
                verbose_name="Date de modification",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="delai_de_paiement",
            field=models.PositiveIntegerField(
                blank=True,
                default=60,
                help_text="Délai de paiement en jours",
                null=True,
                verbose_name="Délai de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Adresse e‑mail du client",
                max_length=254,
                null=True,
                verbose_name="E‑mail",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="fax",
            field=models.CharField(
                blank=True,
                help_text="Numéro de fax (optionnel)",
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Tapez un numéro de téléphone valide",
                        regex="^\\+?\\d{7,15}$",
                    )
                ],
                verbose_name="Fax",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="identifiant_fiscal",
            field=models.CharField(
                blank=True,
                help_text="Identifiant fiscal (IF)",
                max_length=100,
                null=True,
                verbose_name="Identifiant fiscal",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="nom",
            field=models.CharField(
                blank=True,
                help_text="Nom (pour personne physique)",
                max_length=100,
                null=True,
                verbose_name="Nom",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="numero_du_compte",
            field=models.CharField(
                blank=True,
                help_text="Numéro de compte bancaire du client",
                max_length=100,
                null=True,
                verbose_name="Numéro du compte",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="prenom",
            field=models.CharField(
                blank=True,
                help_text="Prénom (pour personne physique)",
                max_length=100,
                null=True,
                verbose_name="Prénom",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="raison_sociale",
            field=models.CharField(
                blank=True,
                help_text="Raison sociale pour les personnes morales",
                max_length=255,
                null=True,
                verbose_name="Raison sociale",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="registre_de_commerce",
            field=models.CharField(
                blank=True,
                help_text="Numéro du registre de commerce",
                max_length=100,
                null=True,
                verbose_name="Registre de commerce",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="remarque",
            field=models.TextField(
                blank=True,
                help_text="Remarque ou note concernant le client",
                null=True,
                verbose_name="Remarque",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="taxe_professionnelle",
            field=models.CharField(
                blank=True,
                help_text="Référence de la taxe professionnelle",
                max_length=100,
                null=True,
                verbose_name="Taxe professionnelle",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="tel",
            field=models.CharField(
                blank=True,
                help_text="Numéro de téléphone principal",
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Tapez un numéro de téléphone valide",
                        regex="^\\+?\\d{7,15}$",
                    )
                ],
                verbose_name="Téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="ville",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Ville du client",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="parameter.ville",
                verbose_name="Ville",
            ),
        ),
    ]
