# Generated by Django 6.0 on 2026-01-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0010_alter_client_cnss_alter_client_ice_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalclient",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "Historique Client",
                "verbose_name_plural": "Historiques Clients",
            },
        ),
    ]
