# Generated by Django 6.0 on 2026-02-06 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0011_alter_historicalclient_options"),
        ("company", "0010_company_uses_foreign_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="code_client",
            field=models.CharField(
                help_text="Code unique identifiant le client par société",
                max_length=50,
                verbose_name="Code client",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Société propriétaire du client",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clients",
                to="company.company",
                verbose_name="Société",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="code_client",
            field=models.CharField(
                help_text="Code unique identifiant le client par société",
                max_length=50,
                verbose_name="Code client",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="company",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Société propriétaire du client",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="company.company",
                verbose_name="Société",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="client",
            unique_together={("code_client", "company")},
        ),
    ]
