# Generated by Django 6.0 on 2026-02-06 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0012_alter_client_code_client_alter_client_company_and_more"),
        ("company", "0010_company_uses_foreign_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="company",
            field=models.ForeignKey(
                help_text="Société propriétaire du client",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clients",
                to="company.company",
                verbose_name="Société",
            ),
        ),
    ]
