# Generated by Django 6.0 on 2026-07-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0013_alter_client_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_type",
            field=models.CharField(
                choices=[
                    ("PM", "Personne morale"),
                    ("PP", "Personne physique"),
                    ("CD", "Client Divers"),
                ],
                help_text="Type : Personne morale (PM), physique (PP), ou client divers (CD)",
                max_length=2,
                verbose_name="Type de client",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="client_type",
            field=models.CharField(
                choices=[
                    ("PM", "Personne morale"),
                    ("PP", "Personne physique"),
                    ("CD", "Client Divers"),
                ],
                help_text="Type : Personne morale (PM), physique (PP), ou client divers (CD)",
                max_length=2,
                verbose_name="Type de client",
            ),
        ),
    ]
