# Generated by Django 6.0.3 on 2026-07-04 09:01

import django.db.models.deletion
import logistique.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("article", "0015_article_article_company_archived_idx"),
        ("client", "0013_alter_client_company"),
        ("company", "0010_company_uses_foreign_currency"),
        ("facture_proforma", "0021_factureproforma_termes_paiement_and_more"),
        ("parameter", "0010_add_company_to_parameters"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalLogisticsOrder",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "numero_commande",
                    models.CharField(
                        max_length=24, verbose_name="Numéro commande logistique"
                    ),
                ),
                (
                    "fournisseur",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Fournisseur",
                    ),
                ),
                (
                    "devise",
                    models.CharField(
                        choices=[
                            ("MAD", "MAD – Dirham Marocain"),
                            ("EUR", "EUR – Euro"),
                            ("USD", "USD – Dollar Américain"),
                        ],
                        db_index=True,
                        default="MAD",
                        max_length=3,
                        verbose_name="Devise",
                    ),
                ),
                ("incoterm", models.CharField(blank=True, default="", max_length=50)),
                ("transport", models.CharField(blank=True, default="", max_length=100)),
                ("conditions_paiement", models.TextField(blank=True, default="")),
                ("date_prevue", models.DateField(blank=True, db_index=True, null=True)),
                ("date_reelle", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("Réception commande", "Réception commande"),
                            ("Commande fournisseur", "Commande fournisseur"),
                            ("Proforma", "Proforma"),
                            ("Titre d'Importation", "Titre d'Importation"),
                            ("Validation", "Validation"),
                            ("Paiement demandé", "Paiement demandé"),
                            ("Paiement effectué", "Paiement effectué"),
                            ("SWIFT / Draft LC", "SWIFT / Draft LC"),
                            ("Envoi SWIFT / Draft LC", "Envoi SWIFT / Draft LC"),
                            ("Production", "Production"),
                            ("Expédition", "Expédition"),
                            ("Documents originaux", "Documents originaux"),
                            ("Transit", "Transit"),
                            ("Dédouanement", "Dédouanement"),
                            ("Réception locale", "Réception locale"),
                            ("Livraison client", "Livraison client"),
                            ("Clôture", "Clôture"),
                            ("Annulé", "Annulé"),
                        ],
                        db_index=True,
                        default="Réception commande",
                        max_length=32,
                    ),
                ),
                (
                    "poids_net",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "poids_brut",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "volume",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "origine_marchandise",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "nature_marchandise",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "numero_domiciliation",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("banque", models.CharField(blank=True, default="", max_length=255)),
                (
                    "montant_titre_importation",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "devise_titre_importation",
                    models.CharField(
                        choices=[
                            ("MAD", "MAD – Dirham Marocain"),
                            ("EUR", "EUR – Euro"),
                            ("USD", "USD – Dollar Américain"),
                        ],
                        default="MAD",
                        max_length=3,
                    ),
                ),
                ("date_titre_importation", models.DateField(blank=True, null=True)),
                (
                    "date_validation_titre_importation",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "statut_titre_importation",
                    models.CharField(
                        choices=[
                            ("À ouvrir", "À ouvrir"),
                            ("Déposé", "Déposé"),
                            ("En attente", "En attente"),
                            ("Validé", "Validé"),
                            ("Refusé", "Refusé"),
                            ("Expiré", "Expiré"),
                            ("Clôturé", "Clôturé"),
                        ],
                        db_index=True,
                        default="À ouvrir",
                        max_length=16,
                    ),
                ),
                (
                    "methode_paiement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LC", "LC"),
                            ("Virement", "Virement"),
                            ("Remise documentaire", "Remise documentaire"),
                        ],
                        default="",
                        max_length=24,
                    ),
                ),
                (
                    "statut_paiement",
                    models.CharField(
                        choices=[
                            ("Non demandé", "Non demandé"),
                            ("En attente", "En attente"),
                            ("Validé", "Validé"),
                            ("Rejeté", "Rejeté"),
                        ],
                        db_index=True,
                        default="Non demandé",
                        max_length=16,
                    ),
                ),
                (
                    "demande_paiement_envoyee_le",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("paiement_valide_le", models.DateTimeField(blank=True, null=True)),
                ("date_paiement", models.DateField(blank=True, null=True)),
                (
                    "montant_paiement",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "reference_paiement",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("date_upload_swift", models.DateTimeField(blank=True, null=True)),
                (
                    "swift_envoye_fournisseur_le",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "cout_achat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cout_transport",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "frais_transit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "frais_douane",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tva",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "livraison_locale",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "autres_frais",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cout_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "titre_importation_file",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "proforma_fournisseur_file",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "justificatifs_file",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "swift_file",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "documents_originaux_file",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("date_updated", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="company.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "demande_paiement_envoyee_par",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "marque",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="parameter.marque",
                        verbose_name="Marque",
                    ),
                ),
                (
                    "paiement_valide_par",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable logistique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique Commande Logistique",
                "verbose_name_plural": "Historiques Commandes Logistiques",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="LogisticsOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_commande",
                    models.CharField(
                        max_length=24, verbose_name="Numéro commande logistique"
                    ),
                ),
                (
                    "fournisseur",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Fournisseur",
                    ),
                ),
                (
                    "devise",
                    models.CharField(
                        choices=[
                            ("MAD", "MAD – Dirham Marocain"),
                            ("EUR", "EUR – Euro"),
                            ("USD", "USD – Dollar Américain"),
                        ],
                        db_index=True,
                        default="MAD",
                        max_length=3,
                        verbose_name="Devise",
                    ),
                ),
                ("incoterm", models.CharField(blank=True, default="", max_length=50)),
                ("transport", models.CharField(blank=True, default="", max_length=100)),
                ("conditions_paiement", models.TextField(blank=True, default="")),
                ("date_prevue", models.DateField(blank=True, db_index=True, null=True)),
                ("date_reelle", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("Réception commande", "Réception commande"),
                            ("Commande fournisseur", "Commande fournisseur"),
                            ("Proforma", "Proforma"),
                            ("Titre d'Importation", "Titre d'Importation"),
                            ("Validation", "Validation"),
                            ("Paiement demandé", "Paiement demandé"),
                            ("Paiement effectué", "Paiement effectué"),
                            ("SWIFT / Draft LC", "SWIFT / Draft LC"),
                            ("Envoi SWIFT / Draft LC", "Envoi SWIFT / Draft LC"),
                            ("Production", "Production"),
                            ("Expédition", "Expédition"),
                            ("Documents originaux", "Documents originaux"),
                            ("Transit", "Transit"),
                            ("Dédouanement", "Dédouanement"),
                            ("Réception locale", "Réception locale"),
                            ("Livraison client", "Livraison client"),
                            ("Clôture", "Clôture"),
                            ("Annulé", "Annulé"),
                        ],
                        db_index=True,
                        default="Réception commande",
                        max_length=32,
                    ),
                ),
                (
                    "poids_net",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "poids_brut",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "volume",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "origine_marchandise",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "nature_marchandise",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "numero_domiciliation",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("banque", models.CharField(blank=True, default="", max_length=255)),
                (
                    "montant_titre_importation",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "devise_titre_importation",
                    models.CharField(
                        choices=[
                            ("MAD", "MAD – Dirham Marocain"),
                            ("EUR", "EUR – Euro"),
                            ("USD", "USD – Dollar Américain"),
                        ],
                        default="MAD",
                        max_length=3,
                    ),
                ),
                ("date_titre_importation", models.DateField(blank=True, null=True)),
                (
                    "date_validation_titre_importation",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "statut_titre_importation",
                    models.CharField(
                        choices=[
                            ("À ouvrir", "À ouvrir"),
                            ("Déposé", "Déposé"),
                            ("En attente", "En attente"),
                            ("Validé", "Validé"),
                            ("Refusé", "Refusé"),
                            ("Expiré", "Expiré"),
                            ("Clôturé", "Clôturé"),
                        ],
                        db_index=True,
                        default="À ouvrir",
                        max_length=16,
                    ),
                ),
                (
                    "methode_paiement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LC", "LC"),
                            ("Virement", "Virement"),
                            ("Remise documentaire", "Remise documentaire"),
                        ],
                        default="",
                        max_length=24,
                    ),
                ),
                (
                    "statut_paiement",
                    models.CharField(
                        choices=[
                            ("Non demandé", "Non demandé"),
                            ("En attente", "En attente"),
                            ("Validé", "Validé"),
                            ("Rejeté", "Rejeté"),
                        ],
                        db_index=True,
                        default="Non demandé",
                        max_length=16,
                    ),
                ),
                (
                    "demande_paiement_envoyee_le",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("paiement_valide_le", models.DateTimeField(blank=True, null=True)),
                ("date_paiement", models.DateField(blank=True, null=True)),
                (
                    "montant_paiement",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "reference_paiement",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("date_upload_swift", models.DateTimeField(blank=True, null=True)),
                (
                    "swift_envoye_fournisseur_le",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "cout_achat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cout_transport",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "frais_transit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "frais_douane",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tva",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "livraison_locale",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "autres_frais",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cout_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "titre_importation_file",
                    models.FileField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        upload_to=logistique.models.get_logistique_document_path,
                    ),
                ),
                (
                    "proforma_fournisseur_file",
                    models.FileField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        upload_to=logistique.models.get_logistique_document_path,
                    ),
                ),
                (
                    "justificatifs_file",
                    models.FileField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        upload_to=logistique.models.get_logistique_document_path,
                    ),
                ),
                (
                    "swift_file",
                    models.FileField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        upload_to=logistique.models.get_logistique_document_path,
                    ),
                ),
                (
                    "documents_originaux_file",
                    models.FileField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        upload_to=logistique.models.get_logistique_document_path,
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commandes_logistiques",
                        to="company.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commandes_logistiques_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "demande_paiement_envoyee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demandes_paiement_logistique_envoyees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "marque",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commandes_logistiques",
                        to="parameter.marque",
                        verbose_name="Marque",
                    ),
                ),
                (
                    "paiement_valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paiements_logistique_valides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commandes_logistiques_responsable",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable logistique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commande logistique",
                "verbose_name_plural": "Commandes logistiques",
                "ordering": ("-date_created",),
            },
        ),
        migrations.CreateModel(
            name="LogisticsOrderEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=120)),
                ("old_value", models.CharField(blank=True, default="", max_length=255)),
                ("new_value", models.CharField(blank=True, default="", max_length=255)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="logistique.logisticsorder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evenements_logistiques",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement logistique",
                "verbose_name_plural": "Événements logistiques",
                "ordering": ("-date_created",),
            },
        ),
        migrations.CreateModel(
            name="LogisticsOrderProforma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commande_proformas",
                        to="logistique.logisticsorder",
                    ),
                ),
                (
                    "proforma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logistique_links",
                        to="facture_proforma.factureproforma",
                    ),
                ),
            ],
            options={
                "unique_together": {("commande", "proforma")},
            },
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="proformas",
            field=models.ManyToManyField(
                blank=True,
                related_name="commandes_logistiques",
                through="logistique.LogisticsOrderProforma",
                to="facture_proforma.factureproforma",
            ),
        ),
        migrations.CreateModel(
            name="LogisticsOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article_reference",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("designation", models.TextField(blank=True, default="")),
                (
                    "marque_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=10)),
                ("prix_achat", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "devise_prix_achat",
                    models.CharField(
                        choices=[
                            ("MAD", "MAD – Dirham Marocain"),
                            ("EUR", "EUR – Euro"),
                            ("USD", "USD – Dollar Américain"),
                        ],
                        default="MAD",
                        max_length=3,
                    ),
                ),
                ("prix_vente", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "devise_prix_vente",
                    models.CharField(
                        choices=[
                            ("MAD", "MAD – Dirham Marocain"),
                            ("EUR", "EUR – Euro"),
                            ("USD", "USD – Dollar Américain"),
                        ],
                        default="MAD",
                        max_length=3,
                    ),
                ),
                (
                    "total_achat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_logistiques",
                        to="article.article",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_logistiques",
                        to="client.client",
                    ),
                ),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="logistique.logisticsorder",
                    ),
                ),
                (
                    "proforma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_logistiques",
                        to="facture_proforma.factureproforma",
                    ),
                ),
                (
                    "source_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_logistiques",
                        to="facture_proforma.factureproformaline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne commande logistique",
                "verbose_name_plural": "Lignes commandes logistiques",
                "indexes": [
                    models.Index(
                        fields=["commande", "proforma"],
                        name="logistique__command_74a2d5_idx",
                    ),
                    models.Index(
                        fields=["article"], name="logistique__article_d09949_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="logisticsorder",
            index=models.Index(
                fields=["company", "statut"], name="logistique__company_bea386_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="logisticsorder",
            index=models.Index(
                fields=["company", "marque"], name="logistique__company_4b8be2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="logisticsorder",
            index=models.Index(
                fields=["company", "statut_paiement"],
                name="logistique__company_102ccf_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="logisticsorder",
            constraint=models.UniqueConstraint(
                fields=("company", "numero_commande"),
                name="unique_logistics_order_number_per_company",
            ),
        ),
    ]
