# Generated by Django 6.0.6 on 2026-08-17 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistique", "0003_command_launch_workflow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="date_proforma_fournisseur",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="delai_proforma_jours",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="devise_proforma_fournisseur",
            field=models.CharField(
                choices=[
                    ("MAD", "MAD – Dirham Marocain"),
                    ("EUR", "EUR – Euro"),
                    ("USD", "USD – Dollar Américain"),
                ],
                default="MAD",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="ecart_prix_proforma",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="ecart_quantite_proforma",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="montant_proforma_fournisseur",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="notes_ecarts_proforma",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="numero_proforma_fournisseur",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="proforma_controlee_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="proforma_controlee_par",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="proforma_validee_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="proforma_validee_par",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="statut_proforma_conformite",
            field=models.CharField(
                choices=[
                    ("En attente", "En attente"),
                    ("En contrôle", "En contrôle"),
                    ("Correction demandée", "Correction demandée"),
                    ("Validée", "Validée"),
                    ("Refusée", "Refusée"),
                ],
                db_index=True,
                default="En attente",
                max_length=24,
                verbose_name="Statut proforma et conformité",
            ),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="date_proforma_fournisseur",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="delai_proforma_jours",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="devise_proforma_fournisseur",
            field=models.CharField(
                choices=[
                    ("MAD", "MAD – Dirham Marocain"),
                    ("EUR", "EUR – Euro"),
                    ("USD", "USD – Dollar Américain"),
                ],
                default="MAD",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="ecart_prix_proforma",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="ecart_quantite_proforma",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="montant_proforma_fournisseur",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="notes_ecarts_proforma",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="numero_proforma_fournisseur",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="proforma_controlee_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="proforma_controlee_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proformas_logistique_controlees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="proforma_validee_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="proforma_validee_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proformas_logistique_validees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="statut_proforma_conformite",
            field=models.CharField(
                choices=[
                    ("En attente", "En attente"),
                    ("En contrôle", "En contrôle"),
                    ("Correction demandée", "Correction demandée"),
                    ("Validée", "Validée"),
                    ("Refusée", "Refusée"),
                ],
                db_index=True,
                default="En attente",
                max_length=24,
                verbose_name="Statut proforma et conformité",
            ),
        ),
    ]
