# Generated by Django 6.0.3 on 2026-08-17 16:46

from django.db import migrations, models


def copy_legacy_payment_currency(apps, schema_editor):
    LogisticsOrder = apps.get_model("logistique", "LogisticsOrder")
    HistoricalLogisticsOrder = apps.get_model(
        "logistique", "HistoricalLogisticsOrder"
    )
    for model in (LogisticsOrder, HistoricalLogisticsOrder):
        rows = model.objects.exclude(statut_paiement="Non demandé")
        for row in rows.iterator():
            currency = row.devise_titre_importation or row.devise or "MAD"
            model.objects.filter(pk=row.pk).update(devise_paiement=currency)


class Migration(migrations.Migration):

    dependencies = [
        (
            "logistique",
            "0004_historicallogisticsorder_date_proforma_fournisseur_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="banque_paiement",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="commentaire_paiement",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="devise_paiement",
            field=models.CharField(
                choices=[
                    ("MAD", "MAD – Dirham Marocain"),
                    ("EUR", "EUR – Euro"),
                    ("USD", "USD – Dollar Américain"),
                ],
                default="MAD",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="banque_paiement",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="commentaire_paiement",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="devise_paiement",
            field=models.CharField(
                choices=[
                    ("MAD", "MAD – Dirham Marocain"),
                    ("EUR", "EUR – Euro"),
                    ("USD", "USD – Dollar Américain"),
                ],
                default="MAD",
                max_length=3,
            ),
        ),
        migrations.RunPython(
            copy_legacy_payment_currency,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
