# Generated by Django 6.0.3 on 2026-08-18 08:04

import django.db.models.deletion
import logistique.models
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


LEGACY_PAYMENT_COMPLETE_STAGES = {
    "Paiement effectué",
    "SWIFT / Draft LC",
    "Envoi SWIFT / Draft LC",
    "Production",
    "Expédition",
    "Documents originaux",
    "Transit",
    "Dédouanement",
    "Réception locale",
    "Livraison client",
    "Clôture",
}


def migrate_legacy_payment_workflow(apps, schema_editor):
    LogisticsOrder = apps.get_model("logistique", "LogisticsOrder")
    HistoricalLogisticsOrder = apps.get_model(
        "logistique", "HistoricalLogisticsOrder"
    )
    Installment = apps.get_model("logistique", "LogisticsPaymentInstallment")
    Membership = apps.get_model("accounts", "Membership")
    accountant_by_company = {}

    def assigned_accountant_id(company_id):
        if company_id not in accountant_by_company:
            membership = (
                Membership.objects.filter(
                    company_id=company_id,
                    role__name="Comptable",
                    user__is_active=True,
                )
                .order_by("user_id")
                .first()
            )
            accountant_by_company[company_id] = (
                membership.user_id if membership else None
            )
        return accountant_by_company[company_id]

    for order in LogisticsOrder.objects.all().iterator():
        payment_complete = (
            order.statut_paiement == "Validé"
            or order.statut in LEGACY_PAYMENT_COMPLETE_STAGES
        )
        payment_pending = order.statut_paiement == "En attente"
        payment_blocked = order.statut_paiement == "Rejeté"
        legacy_payment_currency = order.devise_titre_importation or order.devise or "MAD"
        order.statut_titre_importation = (
            "Titre d'import validé – En attente de paiement"
            if payment_complete or payment_pending
            else "À préparer"
        )

        if payment_complete:
            order.statut_paiement = "Validé"
            order.devise_paiement = legacy_payment_currency
            order.statut_banque_paiement = "Exécuté"
            order.statut_traitement_paiement = "Paiement validé"
        elif payment_pending:
            order.devise_paiement = legacy_payment_currency
            order.statut_banque_paiement = "En validation"
            order.statut_traitement_paiement = "Paiement à traiter"
            order.paiement_assigne_a_id = assigned_accountant_id(order.company_id)
        elif payment_blocked:
            order.statut_paiement = "Non demandé"
            order.devise_paiement = legacy_payment_currency
            order.statut_banque_paiement = "Bloqué"

        paid_amount = order.montant_paiement or Decimal("0")
        if payment_complete and paid_amount <= 0:
            paid_amount = order.montant_titre_importation or Decimal("0")
        planned_amount = order.montant_titre_importation or paid_amount
        due_date = (
            order.date_paiement
            or order.date_titre_importation
            or order.date_prevue
            or order.date_created.date()
        )
        if payment_complete and paid_amount > 0:
            Installment.objects.create(
                commande_id=order.id,
                date_echeance=due_date,
                montant_prevu=paid_amount,
                devise=legacy_payment_currency,
                statut_traitement="Paiement validé",
                date_paiement=order.date_paiement or due_date,
                montant_paye=paid_amount,
                banque=order.banque_paiement,
                reference_bancaire=order.reference_paiement,
                methode_paiement=order.methode_paiement,
                commentaire=order.commentaire_paiement,
                justificatif_file=order.swift_file,
                execution_enregistree_le=order.paiement_valide_le,
                execution_enregistree_par_id=order.paiement_valide_par_id,
                paiement_valide_le=order.paiement_valide_le or order.date_updated,
                paiement_valide_par_id=order.paiement_valide_par_id,
                preuve_envoyee_fournisseur_le=order.swift_envoye_fournisseur_le,
            )
        elif payment_pending and planned_amount > 0:
            Installment.objects.create(
                commande_id=order.id,
                date_echeance=due_date,
                montant_prevu=planned_amount,
                devise=legacy_payment_currency,
            )
        order.save(
            update_fields=[
                "statut_titre_importation",
                "statut_paiement",
                "statut_banque_paiement",
                "statut_traitement_paiement",
                "devise_paiement",
                "paiement_assigne_a",
            ]
        )

    for row in HistoricalLogisticsOrder.objects.all().iterator():
        payment_complete = (
            row.statut_paiement == "Validé"
            or row.statut in LEGACY_PAYMENT_COMPLETE_STAGES
        )
        payment_pending = row.statut_paiement == "En attente"
        payment_blocked = row.statut_paiement == "Rejeté"
        legacy_payment_currency = row.devise_titre_importation or row.devise or "MAD"
        row.statut_titre_importation = (
            "Titre d'import validé – En attente de paiement"
            if payment_complete or payment_pending
            else "À préparer"
        )
        if payment_complete:
            row.statut_paiement = "Validé"
            row.devise_paiement = legacy_payment_currency
            row.statut_banque_paiement = "Exécuté"
            row.statut_traitement_paiement = "Paiement validé"
        elif payment_pending:
            row.devise_paiement = legacy_payment_currency
            row.statut_banque_paiement = "En validation"
            row.statut_traitement_paiement = "Paiement à traiter"
            # Historical snapshots must describe what was known at the time. The
            # current first accountant is assigned only to the live order above.
            row.paiement_assigne_a_id = None
        elif payment_blocked:
            row.statut_paiement = "Non demandé"
            row.devise_paiement = legacy_payment_currency
            row.statut_banque_paiement = "Bloqué"
        row.save(
            update_fields=[
                "statut_titre_importation",
                "statut_paiement",
                "statut_banque_paiement",
                "statut_traitement_paiement",
                "devise_paiement",
                "paiement_assigne_a",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_membership_can_change_document_status_and_more"),
        ("logistique", "0005_historicallogisticsorder_banque_paiement_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="paiement_assigne_a",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="paiement_confirme_reception_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="paiement_confirme_reception_par",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="statut_banque_paiement",
            field=models.CharField(
                choices=[
                    ("À préparer", "À préparer"),
                    ("En validation", "En validation"),
                    ("Banque en cours", "Banque en cours"),
                    ("Exécuté", "Exécuté"),
                    ("Confirmé", "Confirmé"),
                    ("Partiel", "Partiel"),
                    ("Bloqué", "Bloqué"),
                ],
                db_index=True,
                default="À préparer",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="statut_traitement_paiement",
            field=models.CharField(
                choices=[
                    ("Paiement à traiter", "Paiement à traiter"),
                    ("Paiement en cours", "Paiement en cours"),
                    (
                        "Paiement effectué – Justificatif à joindre",
                        "Paiement effectué – Justificatif à joindre",
                    ),
                    ("Paiement validé", "Paiement validé"),
                ],
                db_index=True,
                default="Paiement à traiter",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="paiement_assigne_a",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paiements_logistique_assignes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="paiement_confirme_reception_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="paiement_confirme_reception_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paiements_logistique_reception_confirmes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="statut_banque_paiement",
            field=models.CharField(
                choices=[
                    ("À préparer", "À préparer"),
                    ("En validation", "En validation"),
                    ("Banque en cours", "Banque en cours"),
                    ("Exécuté", "Exécuté"),
                    ("Confirmé", "Confirmé"),
                    ("Partiel", "Partiel"),
                    ("Bloqué", "Bloqué"),
                ],
                db_index=True,
                default="À préparer",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="statut_traitement_paiement",
            field=models.CharField(
                choices=[
                    ("Paiement à traiter", "Paiement à traiter"),
                    ("Paiement en cours", "Paiement en cours"),
                    (
                        "Paiement effectué – Justificatif à joindre",
                        "Paiement effectué – Justificatif à joindre",
                    ),
                    ("Paiement validé", "Paiement validé"),
                ],
                db_index=True,
                default="Paiement à traiter",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="historicallogisticsorder",
            name="statut_paiement",
            field=models.CharField(
                choices=[
                    ("Non demandé", "Non demandé"),
                    ("En attente", "En attente"),
                    ("Validé", "Validé"),
                ],
                db_index=True,
                default="Non demandé",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="historicallogisticsorder",
            name="statut_titre_importation",
            field=models.CharField(
                choices=[
                    ("À préparer", "À préparer"),
                    (
                        "Titre d'import validé – En attente de paiement",
                        "Titre d'import validé – En attente de paiement",
                    ),
                ],
                db_index=True,
                default="À préparer",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="logisticsorder",
            name="statut_paiement",
            field=models.CharField(
                choices=[
                    ("Non demandé", "Non demandé"),
                    ("En attente", "En attente"),
                    ("Validé", "Validé"),
                ],
                db_index=True,
                default="Non demandé",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="logisticsorder",
            name="statut_titre_importation",
            field=models.CharField(
                choices=[
                    ("À préparer", "À préparer"),
                    (
                        "Titre d'import validé – En attente de paiement",
                        "Titre d'import validé – En attente de paiement",
                    ),
                ],
                db_index=True,
                default="À préparer",
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="HistoricalLogisticsPaymentInstallment",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("date_echeance", models.DateField()),
                ("montant_prevu", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "devise",
                    models.CharField(
                        choices=[
                            ("MAD", "MAD – Dirham Marocain"),
                            ("EUR", "EUR – Euro"),
                            ("USD", "USD – Dollar Américain"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "statut_traitement",
                    models.CharField(
                        choices=[
                            ("Paiement à traiter", "Paiement à traiter"),
                            ("Paiement en cours", "Paiement en cours"),
                            (
                                "Paiement effectué – Justificatif à joindre",
                                "Paiement effectué – Justificatif à joindre",
                            ),
                            ("Paiement validé", "Paiement validé"),
                        ],
                        db_index=True,
                        default="Paiement à traiter",
                        max_length=64,
                    ),
                ),
                ("date_paiement", models.DateField(blank=True, null=True)),
                (
                    "montant_paye",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("banque", models.CharField(blank=True, default="", max_length=255)),
                (
                    "reference_bancaire",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "methode_paiement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LC", "LC"),
                            ("Virement", "Virement"),
                            ("Remise documentaire", "Remise documentaire"),
                        ],
                        default="",
                        max_length=24,
                    ),
                ),
                ("commentaire", models.TextField(blank=True, default="")),
                (
                    "justificatif_file",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "execution_enregistree_le",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("paiement_valide_le", models.DateTimeField(blank=True, null=True)),
                (
                    "preuve_envoyee_fournisseur_le",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("reception_confirmee_le", models.DateTimeField(blank=True, null=True)),
                ("date_created", models.DateTimeField(blank=True, editable=False)),
                ("date_updated", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "commande",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="logistique.logisticsorder",
                    ),
                ),
                (
                    "execution_enregistree_par",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paiement_valide_par",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reception_confirmee_par",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique échéance paiement logistique",
                "verbose_name_plural": "Historiques échéances paiement logistique",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="LogisticsPaymentInstallment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_echeance", models.DateField()),
                ("montant_prevu", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "devise",
                    models.CharField(
                        choices=[
                            ("MAD", "MAD – Dirham Marocain"),
                            ("EUR", "EUR – Euro"),
                            ("USD", "USD – Dollar Américain"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "statut_traitement",
                    models.CharField(
                        choices=[
                            ("Paiement à traiter", "Paiement à traiter"),
                            ("Paiement en cours", "Paiement en cours"),
                            (
                                "Paiement effectué – Justificatif à joindre",
                                "Paiement effectué – Justificatif à joindre",
                            ),
                            ("Paiement validé", "Paiement validé"),
                        ],
                        db_index=True,
                        default="Paiement à traiter",
                        max_length=64,
                    ),
                ),
                ("date_paiement", models.DateField(blank=True, null=True)),
                (
                    "montant_paye",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("banque", models.CharField(blank=True, default="", max_length=255)),
                (
                    "reference_bancaire",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "methode_paiement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LC", "LC"),
                            ("Virement", "Virement"),
                            ("Remise documentaire", "Remise documentaire"),
                        ],
                        default="",
                        max_length=24,
                    ),
                ),
                ("commentaire", models.TextField(blank=True, default="")),
                (
                    "justificatif_file",
                    models.FileField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        upload_to=logistique.models.get_logistique_document_path,
                    ),
                ),
                (
                    "execution_enregistree_le",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("paiement_valide_le", models.DateTimeField(blank=True, null=True)),
                (
                    "preuve_envoyee_fournisseur_le",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("reception_confirmee_le", models.DateTimeField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="echeances_paiement",
                        to="logistique.logisticsorder",
                    ),
                ),
                (
                    "execution_enregistree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executions_paiement_logistique_enregistrees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paiement_valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="echeances_paiement_logistique_validees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reception_confirmee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receptions_paiement_fournisseur_confirmees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Échéance paiement logistique",
                "verbose_name_plural": "Échéances paiement logistique",
                "ordering": ("date_echeance", "id"),
                "indexes": [
                    models.Index(
                        fields=["commande", "date_echeance"],
                        name="logistique__command_eabfc2_idx",
                    ),
                    models.Index(
                        fields=["commande", "statut_traitement"],
                        name="logistique__command_e4b65e_idx",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            migrate_legacy_payment_workflow,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
