# Generated by Django 6.0.6 on 2026-08-18 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_legacy_delivery_records(apps, schema_editor):
    LogisticsOrder = apps.get_model("logistique", "LogisticsOrder")
    LogisticsPaymentInstallment = apps.get_model(
        "logistique", "LogisticsPaymentInstallment"
    )
    LogisticsOrderProforma = apps.get_model("logistique", "LogisticsOrderProforma")

    # The former implementation timestamped a button click even when SMTP failed
    # (and supplier proof was not mailed at all). Preserve that trace explicitly,
    # but never present it as a verified delivery or unlock receipt confirmation.
    LogisticsOrder.objects.filter(
        demande_paiement_envoyee_le__isnull=False
    ).update(demande_paiement_email_statut="Historique non vérifié")
    LogisticsPaymentInstallment.objects.filter(
        preuve_envoyee_fournisseur_le__isnull=False
    ).update(preuve_email_statut="Historique non vérifié")

    # Copy only known source addresses. Blank legacy values stay blank rather
    # than inventing an address from the supplier name or brand.
    links = LogisticsOrderProforma.objects.select_related("proforma").iterator()
    for link in links:
        supplier_email = (link.proforma.fournisseur_email or "").strip()
        if supplier_email:
            LogisticsOrder.objects.filter(pk=link.commande_id).update(
                fournisseur_email=supplier_email
            )


class Migration(migrations.Migration):

    dependencies = [
        ("facture_proforma", "0024_factureproforma_fournisseur_email_and_more"),
        ("logistique", "0006_historicallogisticsorder_paiement_assigne_a_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="demande_paiement_email_destinataires",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="demande_paiement_email_erreur",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="demande_paiement_email_statut",
            field=models.CharField(
                choices=[
                    ("Non demandé", "Non demandé"),
                    ("Historique non vérifié", "Historique non vérifié"),
                    ("En attente", "En attente"),
                    ("Envoi en cours", "Envoi en cours"),
                    ("Envoyé", "Envoyé"),
                    ("Échec", "Échec"),
                ],
                db_index=True,
                default="Non demandé",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="demande_paiement_email_tentatives",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="fournisseur_email",
            field=models.EmailField(
                blank=True,
                default="",
                max_length=254,
                verbose_name="E-mail fournisseur",
            ),
        ),
        migrations.AddField(
            model_name="historicallogisticspaymentinstallment",
            name="preuve_email_demandee_par",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicallogisticspaymentinstallment",
            name="preuve_email_destinataire",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="historicallogisticspaymentinstallment",
            name="preuve_email_erreur",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="historicallogisticspaymentinstallment",
            name="preuve_email_statut",
            field=models.CharField(
                choices=[
                    ("Non demandé", "Non demandé"),
                    ("Historique non vérifié", "Historique non vérifié"),
                    ("En attente", "En attente"),
                    ("Envoi en cours", "Envoi en cours"),
                    ("Envoyé", "Envoyé"),
                    ("Échec", "Échec"),
                ],
                db_index=True,
                default="Non demandé",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="historicallogisticspaymentinstallment",
            name="preuve_email_tentatives",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="demande_paiement_email_destinataires",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="demande_paiement_email_erreur",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="demande_paiement_email_statut",
            field=models.CharField(
                choices=[
                    ("Non demandé", "Non demandé"),
                    ("Historique non vérifié", "Historique non vérifié"),
                    ("En attente", "En attente"),
                    ("Envoi en cours", "Envoi en cours"),
                    ("Envoyé", "Envoyé"),
                    ("Échec", "Échec"),
                ],
                db_index=True,
                default="Non demandé",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="demande_paiement_email_tentatives",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="fournisseur_email",
            field=models.EmailField(
                blank=True,
                default="",
                max_length=254,
                verbose_name="E-mail fournisseur",
            ),
        ),
        migrations.AddField(
            model_name="logisticspaymentinstallment",
            name="preuve_email_demandee_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preuves_paiement_fournisseur_demandees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="logisticspaymentinstallment",
            name="preuve_email_destinataire",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="logisticspaymentinstallment",
            name="preuve_email_erreur",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="logisticspaymentinstallment",
            name="preuve_email_statut",
            field=models.CharField(
                choices=[
                    ("Non demandé", "Non demandé"),
                    ("Historique non vérifié", "Historique non vérifié"),
                    ("En attente", "En attente"),
                    ("Envoi en cours", "Envoi en cours"),
                    ("Envoyé", "Envoyé"),
                    ("Échec", "Échec"),
                ],
                db_index=True,
                default="Non demandé",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="logisticspaymentinstallment",
            name="preuve_email_tentatives",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(
            preserve_legacy_delivery_records,
            migrations.RunPython.noop,
        ),
    ]
