# Generated by Django 6.0.6 on 2026-08-18 09:44

from django.db import migrations, models


def correct_already_migrated_legacy_delivery_statuses(apps, schema_editor):
    """Repair local/pre-release databases that ran the initial 0007 draft."""
    LogisticsOrder = apps.get_model("logistique", "LogisticsOrder")
    LogisticsPaymentInstallment = apps.get_model(
        "logistique", "LogisticsPaymentInstallment"
    )
    LogisticsOrder.objects.filter(
        demande_paiement_email_statut="Envoyé",
        demande_paiement_envoyee_le__isnull=False,
        demande_paiement_email_destinataires=[],
    ).update(demande_paiement_email_statut="Historique non vérifié")
    LogisticsPaymentInstallment.objects.filter(
        preuve_email_statut="Envoyé",
        preuve_envoyee_fournisseur_le__isnull=False,
        preuve_email_destinataire="",
    ).update(preuve_email_statut="Historique non vérifié")


class Migration(migrations.Migration):

    dependencies = [
        (
            "logistique",
            "0007_historicallogisticsorder_demande_paiement_email_destinataires_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="demande_paiement_email_prise_en_charge_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="demande_paiement_email_task_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="historicallogisticspaymentinstallment",
            name="preuve_email_prise_en_charge_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicallogisticspaymentinstallment",
            name="preuve_email_task_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="demande_paiement_email_prise_en_charge_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="demande_paiement_email_task_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="logisticspaymentinstallment",
            name="preuve_email_prise_en_charge_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="logisticspaymentinstallment",
            name="preuve_email_task_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.RunPython(
            correct_already_migrated_legacy_delivery_statuses,
            migrations.RunPython.noop,
        ),
    ]
