# Generated by Django 6.0.6 on 2026-08-18 10:01

from django.db import migrations, models


def make_pre_token_queued_deliveries_retryable(apps, schema_editor):
    LogisticsOrder = apps.get_model("logistique", "LogisticsOrder")
    LogisticsPaymentInstallment = apps.get_model(
        "logistique", "LogisticsPaymentInstallment"
    )
    LogisticsOrder.objects.filter(
        demande_paiement_email_statut="En attente"
    ).update(
        demande_paiement_email_statut="Échec",
        demande_paiement_email_erreur=(
            "Envoi à relancer après la mise à jour du système d'e-mail."
        ),
        demande_paiement_email_task_id="",
        demande_paiement_email_prise_en_charge_le=None,
        demande_paiement_email_file_token="",
        demande_paiement_email_mis_en_file_le=None,
    )
    LogisticsPaymentInstallment.objects.filter(
        preuve_email_statut="En attente"
    ).update(
        preuve_email_statut="Échec",
        preuve_email_erreur=(
            "Envoi à relancer après la mise à jour du système d'e-mail."
        ),
        preuve_email_task_id="",
        preuve_email_prise_en_charge_le=None,
        preuve_email_file_token="",
        preuve_email_mise_en_file_le=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        (
            "logistique",
            "0008_historicallogisticsorder_demande_paiement_email_prise_en_charge_le_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="demande_paiement_email_file_token",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="demande_paiement_email_mis_en_file_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicallogisticspaymentinstallment",
            name="preuve_email_file_token",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="historicallogisticspaymentinstallment",
            name="preuve_email_mise_en_file_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="demande_paiement_email_file_token",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="demande_paiement_email_mis_en_file_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="logisticspaymentinstallment",
            name="preuve_email_file_token",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="logisticspaymentinstallment",
            name="preuve_email_mise_en_file_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            make_pre_token_queued_deliveries_retryable,
            migrations.RunPython.noop,
        ),
    ]
