# Generated by Django 6.1.1 on 2026-09-10 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistique", "0011_rename_logistics_user_facing_labels"),
        ("parameter", "0010_add_company_to_parameters"),
    ]

    operations = [
        migrations.AddField(
            model_name="logisticsorderline",
            name="expected_emplacement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lignes_logistiques_attendues",
                to="parameter.emplacement",
                verbose_name="Emplacement de réception prévu",
            ),
        ),
        migrations.AddField(
            model_name="logisticsorderline",
            name="received_quantity",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=10,
                verbose_name="Quantité reçue",
            ),
        ),
    ]
