# Generated by Django 6.1.1 on 2026-09-21

from decimal import Decimal, ROUND_HALF_UP

import django.db.models.deletion
import logistique.models
from django.conf import settings
from django.db import migrations, models


STATUT_CHOICES = [
    ("Réception commande", "Réception commande"),
    ("Commande fournisseur", "Commande fournisseur"),
    ("Proforma", "Proforma"),
    ("Titre d'Importation", "Titre d'Importation"),
    ("Validation", "Validation"),
    ("Paiement demandé", "Paiement demandé"),
    ("Paiement effectué", "Paiement effectué"),
    ("SWIFT / Draft LC", "SWIFT / Draft LC"),
    ("Envoi SWIFT / Draft LC", "Envoi SWIFT / Draft LC"),
    ("Production", "Production"),
    ("Expédition", "Expédition"),
    ("Transit", "Transit"),
    ("Dédouanement", "Dédouanement"),
    ("Réception locale", "Réception locale"),
    ("Livraison client", "Livraison client"),
    ("Clôture", "Clôture"),
    ("Annulé", "Annulé"),
]


def backfill_logistics_fields(apps, schema_editor):
    Order = apps.get_model("logistique", "LogisticsOrder")
    HistoricalOrder = apps.get_model("logistique", "HistoricalLogisticsOrder")
    Installment = apps.get_model("logistique", "LogisticsPaymentInstallment")
    HistoricalInstallment = apps.get_model(
        "logistique", "HistoricalLogisticsPaymentInstallment"
    )

    Order.objects.filter(statut="Documents originaux").update(statut="Expédition")
    HistoricalOrder.objects.filter(statut="Documents originaux").update(
        statut="Expédition"
    )

    for order in Order.objects.prefetch_related("lignes__article").iterator(
        chunk_size=100
    ):
        brand_ids = {
            line.article.marque_id
            for line in order.lignes.all()
            if line.article_id and line.article.marque_id
        }
        if order.marque_id:
            brand_ids.add(order.marque_id)
        if brand_ids:
            order.marques.add(*brand_ids)

    for order in Order.objects.prefetch_related("echeances_paiement").iterator(
        chunk_size=100
    ):
        installments = list(order.echeances_paiement.all())
        if not installments:
            continue
        assigned = Decimal("0")
        for index, installment in enumerate(installments):
            if index == len(installments) - 1:
                percentage = Decimal("100") - assigned
            elif order.montant_titre_importation:
                percentage = (
                    installment.montant_prevu
                    * Decimal("100")
                    / order.montant_titre_importation
                ).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
                assigned += percentage
            else:
                percentage = (Decimal("100") / len(installments)).quantize(
                    Decimal("0.01"), rounding=ROUND_HALF_UP
                )
                assigned += percentage
            installment.pourcentage = percentage
            installment.save(update_fields=["pourcentage"])

    HistoricalInstallment.objects.filter(pourcentage=0).update(
        pourcentage=Decimal("100")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("logistique", "0012_logisticsorderline_expected_emplacement_and_more"),
        ("parameter", "0010_add_company_to_parameters"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="logisticsorder",
            name="statut",
            field=models.CharField(
                choices=STATUT_CHOICES,
                db_index=True,
                default="Réception commande",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="historicallogisticsorder",
            name="statut",
            field=models.CharField(
                choices=STATUT_CHOICES,
                db_index=True,
                default="Réception commande",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="ecart_autre_proforma",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="ecart_autre_proforma",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="avance_pourcentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Avance (%)",
            ),
        ),
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="avance_pourcentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Avance (%)",
            ),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="documents_originaux_requis",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="documents_originaux_requis",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="statut_documents_originaux",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Non renseigné"),
                    ("Demandé", "Demandé"),
                    ("Réceptionné", "Réceptionné"),
                    ("Retourné pour correction", "Retourné pour correction"),
                    ("Refusé", "Refusé"),
                ],
                db_index=True,
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="historicallogisticsorder",
            name="statut_documents_originaux",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Non renseigné"),
                    ("Demandé", "Demandé"),
                    ("Réceptionné", "Réceptionné"),
                    ("Retourné pour correction", "Retourné pour correction"),
                    ("Refusé", "Refusé"),
                ],
                db_index=True,
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="logisticsorder",
            name="marques",
            field=models.ManyToManyField(
                blank=True,
                related_name="dossiers_logistiques",
                to="parameter.marque",
                verbose_name="Marques",
            ),
        ),
        migrations.AddField(
            model_name="logisticspaymentinstallment",
            name="pourcentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="historicallogisticspaymentinstallment",
            name="pourcentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name="LogisticsProcessNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statut", models.CharField(db_index=True, max_length=64)),
                ("remarque", models.TextField()),
                (
                    "fichier",
                    models.FileField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        upload_to=logistique.models.get_logistique_document_path,
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_notes",
                        to="logistique.logisticsorder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remarques_processus_logistique",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Remarque processus logistique",
                "verbose_name_plural": "Remarques processus logistique",
                "ordering": ("-date_created",),
            },
        ),
        migrations.RunPython(backfill_logistics_fields, migrations.RunPython.noop),
    ]
