# Generated by Django 6.0.1 on 2026-01-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentNumberSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        help_text="Type: devis, facture_proforma, facture_client, bon_de_livraison",
                        max_length=20,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        help_text="Année complète (ex: 2025)", verbose_name="Année"
                    ),
                ),
                (
                    "last_number",
                    models.IntegerField(
                        default=0,
                        help_text="Dernier numéro séquentiel généré",
                        verbose_name="Dernier numéro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Séquence de numérotation",
                "verbose_name_plural": "Séquences de numérotation",
                "db_table": "core_document_number_sequence",
                "indexes": [
                    models.Index(
                        fields=["document_type", "year"],
                        name="core_docume_documen_ab0e94_idx",
                    )
                ],
                "unique_together": {("document_type", "year")},
            },
        ),
    ]
