# Generated by Django 6.1.1 on 2026-09-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0003_notification_target_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalnotificationpreference",
            name="low_stock_repeat_hours",
            field=models.PositiveIntegerField(
                default=24, verbose_name="Répéter l'alerte de stock après X heures"
            ),
        ),
        migrations.AddField(
            model_name="historicalnotificationpreference",
            name="notify_low_stock",
            field=models.BooleanField(
                default=True, verbose_name="Notifier le stock minimum"
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="low_stock_repeat_hours",
            field=models.PositiveIntegerField(
                default=24, verbose_name="Répéter l'alerte de stock après X heures"
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_low_stock",
            field=models.BooleanField(
                default=True, verbose_name="Notifier le stock minimum"
            ),
        ),
        migrations.AlterField(
            model_name="historicalnotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("overdue_invoice", "Facture en retard"),
                    ("expiring_quote", "Devis expirant"),
                    ("uninvoiced_bdl", "BL non facturé"),
                    ("status_change", "Changement de statut"),
                    ("document_created", "Document créé"),
                    ("low_stock", "Stock minimum"),
                ],
                max_length=30,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("overdue_invoice", "Facture en retard"),
                    ("expiring_quote", "Devis expirant"),
                    ("uninvoiced_bdl", "BL non facturé"),
                    ("status_change", "Changement de statut"),
                    ("document_created", "Document créé"),
                    ("low_stock", "Stock minimum"),
                ],
                max_length=30,
                verbose_name="Type",
            ),
        ),
    ]
