# Generated by Django 6.1.1 on 2026-10-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_ai", "0002_pendingaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevent",
            name="actor_id",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="actor_label",
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="changed_fields",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="record_id",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="resource",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="source",
            field=models.CharField(default="chat_ai_assistant", max_length=32),
        ),
    ]
