# Generated by Django 6.1.1 on 2026-10-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_ai", "0003_auditevent_actor_id_auditevent_actor_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevent",
            name="instruction_id",
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="pendingaction",
            name="instruction_id",
            field=models.UUIDField(null=True),
        ),
    ]
