# Generated by Django 6.0.1 on 2026-01-27 08:30

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0009_alter_historicalcompany_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalMonthlyObjectives",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "objectif_ca",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Objectif de chiffre d'affaires mensuel (MAD)",
                        max_digits=15,
                        verbose_name="Objectif CA",
                    ),
                ),
                (
                    "objectif_factures",
                    models.IntegerField(
                        default=0,
                        help_text="Objectif de nombre de factures mensuelles",
                        verbose_name="Objectif Factures",
                    ),
                ),
                (
                    "objectif_conversion",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Objectif de taux de conversion des devis (%)",
                        max_digits=5,
                        verbose_name="Objectif Conversion",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Horodatage de la création de l'enregistrement",
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="Horodatage de la dernière modification",
                        verbose_name="Date de modification",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Société concernée par ces objectifs",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="company.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique Objectifs Mensuels",
                "verbose_name_plural": "Historiques Objectifs Mensuels",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="MonthlyObjectives",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "objectif_ca",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Objectif de chiffre d'affaires mensuel (MAD)",
                        max_digits=15,
                        verbose_name="Objectif CA",
                    ),
                ),
                (
                    "objectif_factures",
                    models.IntegerField(
                        default=0,
                        help_text="Objectif de nombre de factures mensuelles",
                        verbose_name="Objectif Factures",
                    ),
                ),
                (
                    "objectif_conversion",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Objectif de taux de conversion des devis (%)",
                        max_digits=5,
                        verbose_name="Objectif Conversion",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Horodatage de la création de l'enregistrement",
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Horodatage de la dernière modification",
                        verbose_name="Date de modification",
                    ),
                ),
                (
                    "company",
                    models.OneToOneField(
                        help_text="Société concernée par ces objectifs",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_objectives",
                        to="company.company",
                        verbose_name="Société",
                    ),
                ),
            ],
            options={
                "verbose_name": "Objectifs Mensuels",
                "verbose_name_plural": "Objectifs Mensuels",
                "ordering": ("-date_created",),
            },
        ),
    ]
