# Generated by Django 6.0.1 on 2026-02-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmonthlyobjectives",
            name="objectif_ca_eur",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Objectif de chiffre d'affaires mensuel (EUR)",
                max_digits=15,
                null=True,
                verbose_name="Objectif CA (EUR)",
            ),
        ),
        migrations.AddField(
            model_name="historicalmonthlyobjectives",
            name="objectif_ca_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Objectif de chiffre d'affaires mensuel (USD)",
                max_digits=15,
                null=True,
                verbose_name="Objectif CA (USD)",
            ),
        ),
        migrations.AddField(
            model_name="monthlyobjectives",
            name="objectif_ca_eur",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Objectif de chiffre d'affaires mensuel (EUR)",
                max_digits=15,
                null=True,
                verbose_name="Objectif CA (EUR)",
            ),
        ),
        migrations.AddField(
            model_name="monthlyobjectives",
            name="objectif_ca_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Objectif de chiffre d'affaires mensuel (USD)",
                max_digits=15,
                null=True,
                verbose_name="Objectif CA (USD)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmonthlyobjectives",
            name="objectif_ca",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Objectif de chiffre d'affaires mensuel (MAD)",
                max_digits=15,
                verbose_name="Objectif CA (MAD)",
            ),
        ),
        migrations.AlterField(
            model_name="monthlyobjectives",
            name="objectif_ca",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Objectif de chiffre d'affaires mensuel (MAD)",
                max_digits=15,
                verbose_name="Objectif CA (MAD)",
            ),
        ),
    ]
