# Generated by Django 5.2.8 on 2025-11-27 13:41

import article.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0004_alter_company_civilite_responsable_and_more"),
        ("parameter", "0003_categorie_emplacement_marque_unite"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Référence"
                    ),
                ),
                ("designation", models.TextField(verbose_name="Désignation")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default=None,
                        max_length=1000,
                        null=True,
                        upload_to=article.models.get_article_image_path,
                        verbose_name="Photo",
                    ),
                ),
                (
                    "prix_achat",
                    models.PositiveIntegerField(default=0, verbose_name="Prix d'achat"),
                ),
                (
                    "prix_vente",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Prix de vente"
                    ),
                ),
                (
                    "tva",
                    models.PositiveIntegerField(default=20, verbose_name="TVA (%)"),
                ),
                (
                    "type_article",
                    models.CharField(
                        choices=[("produit", "Produit"), ("service", "Service")],
                        default="produit",
                        max_length=7,
                        verbose_name="Type d'article",
                    ),
                ),
                (
                    "remarque",
                    models.TextField(blank=True, null=True, verbose_name="Remarque"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "archived",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Archivé"
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="parameter.categorie",
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="company.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "emplacement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="parameter.emplacement",
                        verbose_name="Emplacement",
                    ),
                ),
                (
                    "marque",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="parameter.marque",
                        verbose_name="Marque",
                    ),
                ),
                (
                    "unite",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="parameter.unite",
                        verbose_name="Unité",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ("reference",),
            },
        ),
    ]
