# Generated by Django 5.2.8 on 2025-11-27 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ("-date_created",),
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
            },
        ),
    ]
