# Generated by Django 5.2.8 on 2025-12-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_alter_article_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="type_article",
            field=models.CharField(
                choices=[("Produit", "Produit"), ("Service", "Service")],
                default="produit",
                max_length=7,
                verbose_name="Type d'article",
            ),
        ),
    ]
