# Generated by Django 6.0 on 2026-01-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0003_alter_article_type_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="prix_achat",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="prix_vente",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Prix de vente"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="tva",
            field=models.DecimalField(
                decimal_places=2, default=20, max_digits=5, verbose_name="TVA (%)"
            ),
        ),
    ]
