# Generated by Django 6.0.1 on 2026-01-13 09:18

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0005_article_date_updated"),
        ("company", "0007_company_suspended_historicalcompany"),
        ("parameter", "0005_livrepar"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalArticle",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Référence"
                    ),
                ),
                ("designation", models.TextField(verbose_name="Désignation")),
                (
                    "photo",
                    models.TextField(
                        blank=True,
                        default=None,
                        max_length=1000,
                        null=True,
                        verbose_name="Photo",
                    ),
                ),
                (
                    "prix_achat",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Prix d'achat",
                    ),
                ),
                (
                    "prix_vente",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Prix de vente",
                    ),
                ),
                (
                    "tva",
                    models.DecimalField(
                        decimal_places=2,
                        default=20,
                        max_digits=5,
                        verbose_name="TVA (%)",
                    ),
                ),
                (
                    "type_article",
                    models.CharField(
                        choices=[("Produit", "Produit"), ("Service", "Service")],
                        default="produit",
                        max_length=7,
                        verbose_name="Type d'article",
                    ),
                ),
                (
                    "remarque",
                    models.TextField(blank=True, null=True, verbose_name="Remarque"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        verbose_name="Date de modification",
                    ),
                ),
                (
                    "archived",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Archivé"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="parameter.categorie",
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="company.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "emplacement",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="parameter.emplacement",
                        verbose_name="Emplacement",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "marque",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="parameter.marque",
                        verbose_name="Marque",
                    ),
                ),
                (
                    "unite",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="parameter.unite",
                        verbose_name="Unité",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Article",
                "verbose_name_plural": "historical Articles",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
