# Generated by Django 6.0 on 2026-01-26 11:11

import article.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0006_historicalarticle"),
        ("company", "0008_alter_company_options_and_more"),
        ("parameter", "0008_alter_categorie_nom_alter_emplacement_nom_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="archived",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indique si l'article est archivé",
                verbose_name="Archivé",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="categorie",
            field=models.ForeignKey(
                blank=True,
                help_text="Catégorie de l'article",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="parameter.categorie",
                verbose_name="Catégorie",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="company",
            field=models.ForeignKey(
                help_text="Société propriétaire de l'article",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="company.company",
                verbose_name="Société",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="date_created",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="Horodatage de la création de l'article",
                verbose_name="Date de création",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="date_updated",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Horodatage de la dernière modification",
                verbose_name="Date de modification",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="designation",
            field=models.TextField(
                help_text="Désignation ou description courte de l'article",
                verbose_name="Désignation",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="emplacement",
            field=models.ForeignKey(
                blank=True,
                help_text="Emplacement de stockage",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="parameter.emplacement",
                verbose_name="Emplacement",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="marque",
            field=models.ForeignKey(
                blank=True,
                help_text="Marque de l'article",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="parameter.marque",
                verbose_name="Marque",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="photo",
            field=models.ImageField(
                blank=True,
                default=None,
                help_text="Photo de l'article",
                max_length=1000,
                null=True,
                upload_to=article.models.get_article_image_path,
                verbose_name="Photo",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="prix_achat",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Prix d'achat unitaire",
                max_digits=10,
                verbose_name="Prix d'achat",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="prix_vente",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Prix de vente unitaire",
                max_digits=10,
                verbose_name="Prix de vente",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="reference",
            field=models.CharField(
                help_text="Référence unique de l'article",
                max_length=100,
                unique=True,
                verbose_name="Référence",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="remarque",
            field=models.TextField(
                blank=True,
                help_text="Remarques internes concernant l'article",
                null=True,
                verbose_name="Remarque",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="tva",
            field=models.DecimalField(
                decimal_places=2,
                default=20,
                help_text="Taux de TVA appliqué (en pourcentage)",
                max_digits=5,
                verbose_name="TVA (%)",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="type_article",
            field=models.CharField(
                choices=[("Produit", "Produit"), ("Service", "Service")],
                default="produit",
                help_text="Type : Produit ou Service",
                max_length=7,
                verbose_name="Type d'article",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="unite",
            field=models.ForeignKey(
                blank=True,
                help_text="Unité de mesure (ex: pièce, kg)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="parameter.unite",
                verbose_name="Unité",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarticle",
            name="archived",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indique si l'article est archivé",
                verbose_name="Archivé",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarticle",
            name="categorie",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Catégorie de l'article",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="parameter.categorie",
                verbose_name="Catégorie",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarticle",
            name="company",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Société propriétaire de l'article",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="company.company",
                verbose_name="Société",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarticle",
            name="date_created",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="Horodatage de la création de l'article",
                verbose_name="Date de création",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarticle",
            name="date_updated",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Horodatage de la dernière modification",
                verbose_name="Date de modification",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarticle",
            name="designation",
            field=models.TextField(
                help_text="Désignation ou description courte de l'article",
                verbose_name="Désignation",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarticle",
            name="emplacement",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Emplacement de stockage",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="parameter.emplacement",
                verbose_name="Emplacement",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarticle",
            name="marque",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Marque de l'article",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="parameter.marque",
                verbose_name="Marque",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarticle",
            name="photo",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Photo de l'article",
                max_length=1000,
                null=True,
                verbose_name="Photo",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarticle",
            name="prix_achat",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Prix d'achat unitaire",
                max_digits=10,
                verbose_name="Prix d'achat",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarticle",
            name="prix_vente",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Prix de vente unitaire",
                max_digits=10,
                verbose_name="Prix de vente",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarticle",
            name="reference",
            field=models.CharField(
                db_index=True,
                help_text="Référence unique de l'article",
                max_length=100,
                verbose_name="Référence",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarticle",
            name="remarque",
            field=models.TextField(
                blank=True,
                help_text="Remarques internes concernant l'article",
                null=True,
                verbose_name="Remarque",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarticle",
            name="tva",
            field=models.DecimalField(
                decimal_places=2,
                default=20,
                help_text="Taux de TVA appliqué (en pourcentage)",
                max_digits=5,
                verbose_name="TVA (%)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarticle",
            name="type_article",
            field=models.CharField(
                choices=[("Produit", "Produit"), ("Service", "Service")],
                default="produit",
                help_text="Type : Produit ou Service",
                max_length=7,
                verbose_name="Type d'article",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarticle",
            name="unite",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Unité de mesure (ex: pièce, kg)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="parameter.unite",
                verbose_name="Unité",
            ),
        ),
    ]
