# Generated by Django 6.0 on 2026-01-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0007_alter_article_archived_alter_article_categorie_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalarticle",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "Historique Article",
                "verbose_name_plural": "Historiques Articles",
            },
        ),
    ]
