# Generated by Django 6.0.1 on 2026-02-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0008_alter_historicalarticle_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="devise_prix_achat",
            field=models.CharField(
                choices=[
                    ("MAD", "MAD – Dirham Marocain"),
                    ("EUR", "EUR – Euro"),
                    ("USD", "USD – Dollar Américain"),
                    ("GBP", "GBP – Livre Sterling"),
                    ("CHF", "CHF – Franc Suisse"),
                ],
                default="MAD",
                help_text="Devise utilisée pour le prix d'achat",
                max_length=3,
                verbose_name="Devise prix d'achat",
            ),
        ),
        migrations.AddField(
            model_name="historicalarticle",
            name="devise_prix_achat",
            field=models.CharField(
                choices=[
                    ("MAD", "MAD – Dirham Marocain"),
                    ("EUR", "EUR – Euro"),
                    ("USD", "USD – Dollar Américain"),
                    ("GBP", "GBP – Livre Sterling"),
                    ("CHF", "CHF – Franc Suisse"),
                ],
                default="MAD",
                help_text="Devise utilisée pour le prix d'achat",
                max_length=3,
                verbose_name="Devise prix d'achat",
            ),
        ),
    ]
