# Generated by Django 6.0.1 on 2026-02-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0009_add_devise_prix_achat"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="devise_prix_vente",
            field=models.CharField(
                choices=[
                    ("MAD", "MAD – Dirham Marocain"),
                    ("EUR", "EUR – Euro"),
                    ("USD", "USD – Dollar Américain"),
                ],
                default="MAD",
                help_text="Devise utilisée pour le prix de vente",
                max_length=3,
                verbose_name="Devise prix de vente",
            ),
        ),
        migrations.AddField(
            model_name="historicalarticle",
            name="devise_prix_vente",
            field=models.CharField(
                choices=[
                    ("MAD", "MAD – Dirham Marocain"),
                    ("EUR", "EUR – Euro"),
                    ("USD", "USD – Dollar Américain"),
                ],
                default="MAD",
                help_text="Devise utilisée pour le prix de vente",
                max_length=3,
                verbose_name="Devise prix de vente",
            ),
        ),
    ]
