# Generated by Django 6.0 on 2026-02-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0010_article_devise_prix_vente_and_more"),
        ("company", "0010_company_uses_foreign_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="reference",
            field=models.CharField(
                help_text="Référence unique de l'article par société",
                max_length=100,
                verbose_name="Référence",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarticle",
            name="reference",
            field=models.CharField(
                help_text="Référence unique de l'article par société",
                max_length=100,
                verbose_name="Référence",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="article",
            unique_together={("reference", "company")},
        ),
    ]
