# Generated by Django 6.0.2 on 2026-02-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0012_change_price_decimal_places"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="prix_achat",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Prix d'achat unitaire",
                max_digits=10,
                verbose_name="Prix d'achat",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="prix_vente",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Prix de vente unitaire",
                max_digits=10,
                verbose_name="Prix de vente",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarticle",
            name="prix_achat",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Prix d'achat unitaire",
                max_digits=10,
                verbose_name="Prix d'achat",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarticle",
            name="prix_vente",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Prix de vente unitaire",
                max_digits=10,
                verbose_name="Prix de vente",
            ),
        ),
    ]
