# Generated by Django 6.0.2 on 2026-02-16 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0013_revert_to_2_decimal_places"),
        ("company", "0010_company_uses_foreign_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="company",
            field=models.ForeignKey(
                help_text="Société propriétaire de l'article",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="articles",
                to="company.company",
                verbose_name="Société",
            ),
        ),
    ]
