# Generated by Django 6.0.2 on 2026-02-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0014_alter_article_company"),
        ("company", "0010_company_uses_foreign_currency"),
        ("parameter", "0010_add_company_to_parameters"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["company", "archived"], name="article_company_archived_idx"
            ),
        ),
    ]
