# Generated by Django 6.1.1 on 2026-09-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0015_article_article_company_archived_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="stock_minimum",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Seuil d'alerte. La valeur 0 désactive l'alerte.",
                max_digits=12,
                verbose_name="Stock minimum",
            ),
        ),
        migrations.AddField(
            model_name="historicalarticle",
            name="stock_minimum",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Seuil d'alerte. La valeur 0 désactive l'alerte.",
                max_digits=12,
                verbose_name="Stock minimum",
            ),
        ),
    ]
