# Generated by Django 6.0 on 2025-12-17 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("article", "0003_alter_article_type_article"),
        ("client", "0007_alter_client_options"),
        ("parameter", "0004_modepaiement_modereglement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FactureClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_facture",
                    models.CharField(
                        help_text="Format ex: 0001/25",
                        max_length=20,
                        unique=True,
                        verbose_name="Numéro de la facture client",
                    ),
                ),
                (
                    "date_facture",
                    models.DateField(db_index=True, verbose_name="Date de facture"),
                ),
                (
                    "numero_bon_commande_client",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Numéro de bon de commande client",
                    ),
                ),
                (
                    "remarque",
                    models.TextField(blank=True, null=True, verbose_name="Remarque"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("Brouillon", "Brouillon"),
                            ("Envoyé", "Envoyé"),
                            ("Accepté", "Accepté"),
                            ("Refusé", "Refusé"),
                            ("Annulé", "Annulé"),
                            ("Expiré", "Expiré"),
                        ],
                        default="Brouillon",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "total_ht",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="Somme des totaux des lignes avant TVA",
                        verbose_name="Total HT",
                    ),
                ),
                (
                    "total_tva",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="Montant total de la TVA",
                        verbose_name="Total TVA",
                    ),
                ),
                (
                    "total_ttc",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="Total toutes taxes comprises (TTC)",
                        verbose_name="Total TTC",
                    ),
                ),
                (
                    "remise_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("Pourcentage", "Pourcentage"),
                            ("Fixe", "Fixe"),
                        ],
                        default="",
                        help_text="Type de remise appliquée : 'Pourcentage' ou 'Fixe'",
                        max_length=12,
                        null=True,
                        verbose_name="Type de remise",
                    ),
                ),
                (
                    "remise",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Valeur de la remise appliquée",
                        verbose_name="Valeur remise",
                    ),
                ),
                (
                    "total_ttc_apres_remise",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="Total TTC après application de la remise",
                        verbose_name="Total TTC après remise",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par l'utilisateur",
                    ),
                ),
                (
                    "mode_paiement",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="parameter.modepaiement",
                        verbose_name="Mode de paiement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture Client",
                "verbose_name_plural": "Factures Client",
                "ordering": ("-date_created",),
            },
        ),
        migrations.CreateModel(
            name="FactureClientLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prix_achat",
                    models.PositiveIntegerField(
                        help_text="Prix d'achat unitaire (entier positif, ex: en MAD)",
                        verbose_name="Prix d'achat",
                    ),
                ),
                (
                    "prix_vente",
                    models.PositiveIntegerField(
                        help_text="Prix de vente unitaire (entier positif, ex: en MAD)",
                        verbose_name="Prix de vente",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Quantité (entier positif)",
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "remise_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("Pourcentage", "Pourcentage"),
                            ("Fixe", "Fixe"),
                        ],
                        default="",
                        help_text="Type de remise appliquée : 'Pourcentage' ou 'Fixe'",
                        max_length=12,
                        null=True,
                        verbose_name="Type de remise",
                    ),
                ),
                (
                    "remise",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Valeur après application de la remise",
                        verbose_name="Valeur remise",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="article.article",
                        verbose_name="Article",
                    ),
                ),
                (
                    "facture_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="facture_client.factureclient",
                        verbose_name="Facture Client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de facture Client",
                "verbose_name_plural": "Lignes de factures Client",
            },
        ),
    ]
