# Generated by Django 6.0 on 2025-12-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facture_client", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factureclient",
            name="remise",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Valeur de la remise appliquée",
                max_digits=10,
                verbose_name="Valeur remise",
            ),
        ),
        migrations.AlterField(
            model_name="factureclientline",
            name="remise",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Valeur de la remise appliquée",
                max_digits=10,
                verbose_name="Valeur remise",
            ),
        ),
    ]
