# Generated by Django 6.0.1 on 2026-01-21 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0006_historicalarticle"),
        ("client", "0009_historicalclient"),
        ("facture_client", "0005_historicalfactureclient_historicalfactureclientline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factureclient",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="client.client",
                verbose_name="Client",
            ),
        ),
        migrations.AlterField(
            model_name="factureclientline",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="article.article",
                verbose_name="Article",
            ),
        ),
    ]
