# Generated by Django 6.0 on 2026-01-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facture_client", "0007_alter_factureclient_client_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalfactureclient",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "Historique Facture Client",
                "verbose_name_plural": "Historiques Factures Client",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalfactureclientline",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "Historique Facture Client",
                "verbose_name_plural": "Historiques Factures Client",
            },
        ),
    ]
