# Generated by Django 6.0 on 2026-02-06 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0010_company_uses_foreign_currency"),
        ("facture_client", "0010_factureclient_devise_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="factureclient",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Société propriétaire de la facture",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="factures_client",
                to="company.company",
                verbose_name="Société",
            ),
        ),
        migrations.AddField(
            model_name="historicalfactureclient",
            name="company",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Société propriétaire de la facture",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="company.company",
                verbose_name="Société",
            ),
        ),
        migrations.AlterField(
            model_name="factureclient",
            name="numero_facture",
            field=models.CharField(
                help_text="Format ex: 0001/25",
                max_length=20,
                verbose_name="Numéro de la facture client",
            ),
        ),
        migrations.AlterField(
            model_name="historicalfactureclient",
            name="numero_facture",
            field=models.CharField(
                help_text="Format ex: 0001/25",
                max_length=20,
                verbose_name="Numéro de la facture client",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="factureclient",
            unique_together={("numero_facture", "company")},
        ),
    ]
