# Generated by Django 6.0 on 2026-02-06 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0010_company_uses_foreign_currency"),
        ("facture_client", "0012_alter_factureclient_mode_paiement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factureclient",
            name="company",
            field=models.ForeignKey(
                help_text="Société propriétaire de la facture",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="factures_client",
                to="company.company",
                verbose_name="Société",
            ),
        ),
    ]
