# Generated by Django 6.0.2 on 2026-02-16 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0013_alter_client_company"),
        ("company", "0010_company_uses_foreign_currency"),
        ("facture_client", "0014_alter_factureclient_devise_and_more"),
        ("parameter", "0010_add_company_to_parameters"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="factureclient",
            index=models.Index(
                fields=["company", "date_facture"],
                name="facture_cli_company_1b551e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="factureclient",
            index=models.Index(
                fields=["client", "company"], name="facture_cli_client__72efbc_idx"
            ),
        ),
    ]
