# Generated by Django 6.0.3 on 2026-03-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facture_client", "0017_recalculate_totals_remise_on_ht"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factureclient",
            name="total_ttc",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text="Total TTC final (HT après remise + TVA sur HT après remise)",
                max_digits=10,
                verbose_name="Total TTC",
            ),
        ),
        migrations.AlterField(
            model_name="factureclient",
            name="total_ttc_apres_remise",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text="Total TTC après application de la remise (identique à total_ttc)",
                max_digits=10,
                verbose_name="Total TTC après remise",
            ),
        ),
        migrations.AlterField(
            model_name="factureclient",
            name="total_tva",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text="Montant total de la TVA (calculé sur le HT après remise globale)",
                max_digits=10,
                verbose_name="Total TVA",
            ),
        ),
        migrations.AlterField(
            model_name="historicalfactureclient",
            name="total_ttc",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text="Total TTC final (HT après remise + TVA sur HT après remise)",
                max_digits=10,
                verbose_name="Total TTC",
            ),
        ),
        migrations.AlterField(
            model_name="historicalfactureclient",
            name="total_ttc_apres_remise",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text="Total TTC après application de la remise (identique à total_ttc)",
                max_digits=10,
                verbose_name="Total TTC après remise",
            ),
        ),
        migrations.AlterField(
            model_name="historicalfactureclient",
            name="total_tva",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text="Montant total de la TVA (calculé sur le HT après remise globale)",
                max_digits=10,
                verbose_name="Total TVA",
            ),
        ),
    ]
