# Generated by Django 6.0.6 on 2026-06-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facture_client", "0019_factureclient_date_echeance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="factureclient",
            name="termes_paiement",
            field=models.TextField(
                blank=True,
                help_text="Conditions ou termes de paiement de la facture",
                null=True,
                verbose_name="Termes de paiement",
            ),
        ),
        migrations.AddField(
            model_name="historicalfactureclient",
            name="termes_paiement",
            field=models.TextField(
                blank=True,
                help_text="Conditions ou termes de paiement de la facture",
                null=True,
                verbose_name="Termes de paiement",
            ),
        ),
    ]
