# Generated by Django 6.0.3 on 2026-08-18 10:49

import django.db.models.deletion
from django.db import migrations, models


def backfill_supplier_from_source(apps, schema_editor):
    FactureClient = apps.get_model("facture_client", "FactureClient")
    FactureProForma = apps.get_model("facture_proforma", "FactureProForma")

    for invoice in FactureClient.objects.exclude(source_proforma_id=None).iterator():
        source = (
            FactureProForma.objects.filter(pk=invoice.source_proforma_id)
            .values("fournisseur", "fournisseur_email")
            .first()
        )
        if not source:
            continue
        updates = {}
        if not invoice.fournisseur and source["fournisseur"]:
            updates["fournisseur"] = source["fournisseur"]
        if not invoice.fournisseur_email and source["fournisseur_email"]:
            updates["fournisseur_email"] = source["fournisseur_email"]
        if updates:
            FactureClient.objects.filter(pk=invoice.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ("devi", "0026_devi_fournisseur_devi_fournisseur_email_and_more"),
        ("facture_client", "0021_factureclient_source_proforma_and_more"),
        ("facture_proforma", "0025_alter_factureproforma_fournisseur_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="factureclient",
            name="fournisseur",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Fournisseur interne repris lors des conversions",
                max_length=255,
                verbose_name="Fournisseur",
            ),
        ),
        migrations.AddField(
            model_name="factureclient",
            name="fournisseur_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Adresse interne reprise lors des conversions",
                max_length=254,
                verbose_name="E-mail fournisseur",
            ),
        ),
        migrations.AddField(
            model_name="factureclient",
            name="source_devis",
            field=models.ForeignKey(
                blank=True,
                help_text="Devis ayant généré directement cette facture client",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="converted_factures_client",
                to="devi.devi",
                verbose_name="Devis d'origine",
            ),
        ),
        migrations.AddField(
            model_name="historicalfactureclient",
            name="fournisseur",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Fournisseur interne repris lors des conversions",
                max_length=255,
                verbose_name="Fournisseur",
            ),
        ),
        migrations.AddField(
            model_name="historicalfactureclient",
            name="fournisseur_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Adresse interne reprise lors des conversions",
                max_length=254,
                verbose_name="E-mail fournisseur",
            ),
        ),
        migrations.AddField(
            model_name="historicalfactureclient",
            name="source_devis",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Devis ayant généré directement cette facture client",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="devi.devi",
                verbose_name="Devis d'origine",
            ),
        ),
        migrations.RunPython(backfill_supplier_from_source, migrations.RunPython.noop),
    ]
