# Generated by Django 6.0 on 2026-01-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bon_de_livraison", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bondelivraison",
            name="total_ht",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text="Somme des totaux des lignes avant TVA",
                max_digits=10,
                verbose_name="Total HT",
            ),
        ),
        migrations.AlterField(
            model_name="bondelivraison",
            name="total_ttc",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text="Total toutes taxes comprises (TTC)",
                max_digits=10,
                verbose_name="Total TTC",
            ),
        ),
        migrations.AlterField(
            model_name="bondelivraison",
            name="total_ttc_apres_remise",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text="Total TTC après application de la remise",
                max_digits=10,
                verbose_name="Total TTC après remise",
            ),
        ),
        migrations.AlterField(
            model_name="bondelivraison",
            name="total_tva",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text="Montant total de la TVA",
                max_digits=10,
                verbose_name="Total TVA",
            ),
        ),
    ]
