# Generated by Django 6.0 on 2026-01-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bon_de_livraison", "0002_alter_bondelivraison_total_ht_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bondelivraison",
            name="statut",
            field=models.CharField(
                choices=[
                    ("Brouillon", "Brouillon"),
                    ("Envoyé", "Envoyé"),
                    ("Accepté", "Accepté"),
                    ("Refusé", "Refusé"),
                    ("Annulé", "Annulé"),
                    ("Expiré", "Expiré"),
                    ("Facturé", "Facturé"),
                ],
                default="Brouillon",
                max_length=10,
                verbose_name="Statut",
            ),
        ),
    ]
