# Generated by Django 6.0.1 on 2026-01-21 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0006_historicalarticle"),
        ("bon_de_livraison", "0004_historicalbondelivraison_and_more"),
        ("client", "0009_historicalclient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bondelivraison",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="client.client",
                verbose_name="Client",
            ),
        ),
        migrations.AlterField(
            model_name="bondelivraisonline",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="article.article",
                verbose_name="Article",
            ),
        ),
    ]
