# Generated by Django 6.0 on 2026-01-26 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0007_alter_article_archived_alter_article_categorie_and_more"),
        ("bon_de_livraison", "0005_alter_bondelivraison_client_and_more"),
        ("client", "0010_alter_client_cnss_alter_client_ice_and_more"),
        ("parameter", "0008_alter_categorie_nom_alter_emplacement_nom_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="bondelivraison",
            name="client",
            field=models.ForeignKey(
                help_text="Client associé au document",
                on_delete=django.db.models.deletion.PROTECT,
                to="client.client",
                verbose_name="Client",
            ),
        ),
        migrations.AlterField(
            model_name="bondelivraison",
            name="created_by_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Utilisateur ayant créé le document",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par l'utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="bondelivraison",
            name="date_bon_livraison",
            field=models.DateField(
                db_index=True,
                help_text="Date d'émission du bon de livraison",
                verbose_name="Date du bon de livraison",
            ),
        ),
        migrations.AlterField(
            model_name="bondelivraison",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Horodatage de la création du document",
                verbose_name="Date de création",
            ),
        ),
        migrations.AlterField(
            model_name="bondelivraison",
            name="date_updated",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Horodatage de la dernière modification du document",
                verbose_name="Date de mise à jour",
            ),
        ),
        migrations.AlterField(
            model_name="bondelivraison",
            name="livre_par",
            field=models.ForeignKey(
                blank=True,
                help_text="Livreur ayant effectué la livraison",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="parameter.livrepar",
                verbose_name="Livré par",
            ),
        ),
        migrations.AlterField(
            model_name="bondelivraison",
            name="mode_paiement",
            field=models.ForeignKey(
                help_text="Mode de paiement préféré pour le document",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="parameter.modepaiement",
                verbose_name="Mode de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="bondelivraison",
            name="numero_bon_commande_client",
            field=models.CharField(
                blank=True,
                help_text="Numéro du bon de commande client (optionnel)",
                max_length=50,
                null=True,
                verbose_name="Numéro de bon de commande client",
            ),
        ),
        migrations.AlterField(
            model_name="bondelivraison",
            name="remarque",
            field=models.TextField(
                blank=True,
                help_text="Remarque ou note supplémentaire pour le document",
                null=True,
                verbose_name="Remarque",
            ),
        ),
        migrations.AlterField(
            model_name="bondelivraison",
            name="statut",
            field=models.CharField(
                choices=[
                    ("Brouillon", "Brouillon"),
                    ("Envoyé", "Envoyé"),
                    ("Accepté", "Accepté"),
                    ("Refusé", "Refusé"),
                    ("Annulé", "Annulé"),
                    ("Expiré", "Expiré"),
                    ("Facturé", "Facturé"),
                ],
                default="Brouillon",
                help_text="Statut du bon de livraison",
                max_length=10,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="bondelivraisonline",
            name="article",
            field=models.ForeignKey(
                help_text="Article livré",
                on_delete=django.db.models.deletion.PROTECT,
                to="article.article",
                verbose_name="Article",
            ),
        ),
        migrations.AlterField(
            model_name="bondelivraisonline",
            name="bon_de_livraison",
            field=models.ForeignKey(
                help_text="Bon de livraison parent associé à cette ligne",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lignes",
                to="bon_de_livraison.bondelivraison",
                verbose_name="Bon de Livraison",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbondelivraison",
            name="client",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Client associé au document",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="client.client",
                verbose_name="Client",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbondelivraison",
            name="created_by_user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Utilisateur ayant créé le document",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par l'utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbondelivraison",
            name="date_bon_livraison",
            field=models.DateField(
                db_index=True,
                help_text="Date d'émission du bon de livraison",
                verbose_name="Date du bon de livraison",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbondelivraison",
            name="date_created",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Horodatage de la création du document",
                verbose_name="Date de création",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbondelivraison",
            name="date_updated",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Horodatage de la dernière modification du document",
                verbose_name="Date de mise à jour",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbondelivraison",
            name="livre_par",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Livreur ayant effectué la livraison",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="parameter.livrepar",
                verbose_name="Livré par",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbondelivraison",
            name="mode_paiement",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Mode de paiement préféré pour le document",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="parameter.modepaiement",
                verbose_name="Mode de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbondelivraison",
            name="numero_bon_commande_client",
            field=models.CharField(
                blank=True,
                help_text="Numéro du bon de commande client (optionnel)",
                max_length=50,
                null=True,
                verbose_name="Numéro de bon de commande client",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbondelivraison",
            name="remarque",
            field=models.TextField(
                blank=True,
                help_text="Remarque ou note supplémentaire pour le document",
                null=True,
                verbose_name="Remarque",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbondelivraison",
            name="statut",
            field=models.CharField(
                choices=[
                    ("Brouillon", "Brouillon"),
                    ("Envoyé", "Envoyé"),
                    ("Accepté", "Accepté"),
                    ("Refusé", "Refusé"),
                    ("Annulé", "Annulé"),
                    ("Expiré", "Expiré"),
                    ("Facturé", "Facturé"),
                ],
                default="Brouillon",
                help_text="Statut du bon de livraison",
                max_length=10,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbondelivraisonline",
            name="article",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Article livré",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="article.article",
                verbose_name="Article",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbondelivraisonline",
            name="bon_de_livraison",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Bon de livraison parent associé à cette ligne",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="bon_de_livraison.bondelivraison",
                verbose_name="Bon de Livraison",
            ),
        ),
    ]
