# Generated by Django 6.0 on 2026-01-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bon_de_livraison", "0006_alter_bondelivraison_client_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalbondelivraison",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "Historique Bon de Livraison",
                "verbose_name_plural": "Historiques Bons de Livraison",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalbondelivraisonline",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "Historique Ligne de bon de livraison",
                "verbose_name_plural": "Historiques Lignes de bons de livraison",
            },
        ),
    ]
