# Generated by Django 6.0.1 on 2026-02-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bon_de_livraison", "0008_bondelivraisonline_devise_prix_achat"),
    ]

    operations = [
        migrations.AddField(
            model_name="bondelivraison",
            name="devise",
            field=models.CharField(
                choices=[
                    ("MAD", "MAD – Dirham Marocain"),
                    ("EUR", "EUR – Euro"),
                    ("USD", "USD – Dollar Américain"),
                ],
                default="MAD",
                help_text="Devise utilisée pour ce document (héritée du premier article ajouté)",
                max_length=3,
                verbose_name="Devise",
            ),
        ),
        migrations.AddField(
            model_name="bondelivraisonline",
            name="devise_prix_vente",
            field=models.CharField(
                choices=[
                    ("MAD", "MAD – Dirham Marocain"),
                    ("EUR", "EUR – Euro"),
                    ("USD", "USD – Dollar Américain"),
                ],
                default="MAD",
                help_text="Devise utilisée pour le prix de vente",
                max_length=3,
                verbose_name="Devise prix de vente",
            ),
        ),
        migrations.AddField(
            model_name="historicalbondelivraison",
            name="devise",
            field=models.CharField(
                choices=[
                    ("MAD", "MAD – Dirham Marocain"),
                    ("EUR", "EUR – Euro"),
                    ("USD", "USD – Dollar Américain"),
                ],
                default="MAD",
                help_text="Devise utilisée pour ce document (héritée du premier article ajouté)",
                max_length=3,
                verbose_name="Devise",
            ),
        ),
        migrations.AddField(
            model_name="historicalbondelivraisonline",
            name="devise_prix_vente",
            field=models.CharField(
                choices=[
                    ("MAD", "MAD – Dirham Marocain"),
                    ("EUR", "EUR – Euro"),
                    ("USD", "USD – Dollar Américain"),
                ],
                default="MAD",
                help_text="Devise utilisée pour le prix de vente",
                max_length=3,
                verbose_name="Devise prix de vente",
            ),
        ),
    ]
