# Generated by Django 6.0 on 2026-02-06 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bon_de_livraison", "0009_bondelivraison_devise_and_more"),
        ("company", "0010_company_uses_foreign_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="bondelivraison",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Société propriétaire du bon de livraison",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bons_de_livraison",
                to="company.company",
                verbose_name="Société",
            ),
        ),
        migrations.AddField(
            model_name="historicalbondelivraison",
            name="company",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Société propriétaire du bon de livraison",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="company.company",
                verbose_name="Société",
            ),
        ),
        migrations.AlterField(
            model_name="bondelivraison",
            name="numero_bon_livraison",
            field=models.CharField(
                help_text="Format ex: 0001/25",
                max_length=20,
                verbose_name="Numéro du bon de livraison",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbondelivraison",
            name="numero_bon_livraison",
            field=models.CharField(
                help_text="Format ex: 0001/25",
                max_length=20,
                verbose_name="Numéro du bon de livraison",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bondelivraison",
            unique_together={("numero_bon_livraison", "company")},
        ),
    ]
