# Generated by Django 6.0 on 2026-02-06 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bon_de_livraison", "0011_alter_bondelivraison_mode_paiement"),
        ("company", "0010_company_uses_foreign_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bondelivraison",
            name="company",
            field=models.ForeignKey(
                help_text="Société propriétaire du bon de livraison",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bons_de_livraison",
                to="company.company",
                verbose_name="Société",
            ),
        ),
    ]
