# Generated by Django 6.0 on 2026-02-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bon_de_livraison", "0012_alter_bondelivraison_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bondelivraison",
            name="devise",
            field=models.CharField(
                choices=[
                    ("MAD", "MAD – Dirham Marocain"),
                    ("EUR", "EUR – Euro"),
                    ("USD", "USD – Dollar Américain"),
                ],
                db_index=True,
                default="MAD",
                help_text="Devise utilisée pour ce document (héritée du premier article ajouté)",
                max_length=3,
                verbose_name="Devise",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbondelivraison",
            name="devise",
            field=models.CharField(
                choices=[
                    ("MAD", "MAD – Dirham Marocain"),
                    ("EUR", "EUR – Euro"),
                    ("USD", "USD – Dollar Américain"),
                ],
                db_index=True,
                default="MAD",
                help_text="Devise utilisée pour ce document (héritée du premier article ajouté)",
                max_length=3,
                verbose_name="Devise",
            ),
        ),
    ]
