# Generated by Django 6.0.2 on 2026-02-16 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bon_de_livraison", "0013_alter_bondelivraison_devise_and_more"),
        ("client", "0013_alter_client_company"),
        ("company", "0010_company_uses_foreign_currency"),
        ("parameter", "0010_add_company_to_parameters"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bondelivraison",
            index=models.Index(
                fields=["company", "date_bon_livraison"],
                name="bon_de_livr_company_3da1e4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bondelivraison",
            index=models.Index(
                fields=["client", "company"], name="bon_de_livr_client__efa696_idx"
            ),
        ),
    ]
