# Generated by Django 6.0.2 on 2026-02-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bon_de_livraison",
            "0014_bondelivraison_bon_de_livr_company_3da1e4_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bondelivraisonline",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Quantité (ex: 15,35)",
                max_digits=10,
                verbose_name="Quantité",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbondelivraisonline",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Quantité (ex: 15,35)",
                max_digits=10,
                verbose_name="Quantité",
            ),
        ),
    ]
