# Generated by Django 6.0.3 on 2026-08-18 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bon_de_livraison", "0018_bondelivraison_date_echeance_and_more"),
        ("facture_client", "0022_factureclient_fournisseur_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bondelivraison",
            name="fournisseur",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Fournisseur interne repris lors des conversions",
                max_length=255,
                verbose_name="Fournisseur",
            ),
        ),
        migrations.AddField(
            model_name="bondelivraison",
            name="fournisseur_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Adresse interne reprise lors des conversions",
                max_length=254,
                verbose_name="E-mail fournisseur",
            ),
        ),
        migrations.AddField(
            model_name="bondelivraison",
            name="source_facture_client",
            field=models.ForeignKey(
                blank=True,
                help_text="Facture client ayant généré ce bon de livraison",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="converted_bons_livraison",
                to="facture_client.factureclient",
                verbose_name="Facture client d'origine",
            ),
        ),
        migrations.AddField(
            model_name="historicalbondelivraison",
            name="fournisseur",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Fournisseur interne repris lors des conversions",
                max_length=255,
                verbose_name="Fournisseur",
            ),
        ),
        migrations.AddField(
            model_name="historicalbondelivraison",
            name="fournisseur_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Adresse interne reprise lors des conversions",
                max_length=254,
                verbose_name="E-mail fournisseur",
            ),
        ),
        migrations.AddField(
            model_name="historicalbondelivraison",
            name="source_facture_client",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Facture client ayant généré ce bon de livraison",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="facture_client.factureclient",
                verbose_name="Facture client d'origine",
            ),
        ),
    ]
