# Generated by Django 6.0 on 2025-12-17 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facture_proforma", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="factureproforma",
            options={
                "ordering": ("-date_created",),
                "verbose_name": "Facture Pro-Forma",
                "verbose_name_plural": "Factures Pro-Forma",
            },
        ),
        migrations.AlterModelOptions(
            name="factureproformaline",
            options={
                "verbose_name": "Ligne de facture Pro-forma",
                "verbose_name_plural": "Lignes de factures Pro-forma",
            },
        ),
    ]
