# Generated by Django 6.0 on 2025-12-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facture_proforma", "0002_alter_factureproforma_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factureproforma",
            name="remise",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Valeur de la remise appliquée",
                max_digits=10,
                verbose_name="Valeur remise",
            ),
        ),
        migrations.AlterField(
            model_name="factureproformaline",
            name="remise",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Valeur de la remise appliquée",
                max_digits=10,
                verbose_name="Valeur remise",
            ),
        ),
    ]
