# Generated by Django 6.0 on 2026-01-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facture_proforma", "0008_alter_factureproforma_client_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalfactureproforma",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "Historique Facture Pro-Forma",
                "verbose_name_plural": "Historiques Factures Pro-Forma",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalfactureproformaline",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "Historique Facture Pro-Forma",
                "verbose_name_plural": "Historiques Factures Pro-Forma",
            },
        ),
    ]
