# Generated by Django 6.0.1 on 2026-02-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facture_proforma", "0009_alter_historicalfactureproforma_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="factureproformaline",
            name="devise_prix_achat",
            field=models.CharField(
                choices=[
                    ("MAD", "MAD – Dirham Marocain"),
                    ("EUR", "EUR – Euro"),
                    ("USD", "USD – Dollar Américain"),
                ],
                default="MAD",
                help_text="Devise utilisée pour le prix d'achat",
                max_length=3,
                verbose_name="Devise prix d'achat",
            ),
        ),
        migrations.AddField(
            model_name="historicalfactureproformaline",
            name="devise_prix_achat",
            field=models.CharField(
                choices=[
                    ("MAD", "MAD – Dirham Marocain"),
                    ("EUR", "EUR – Euro"),
                    ("USD", "USD – Dollar Américain"),
                ],
                default="MAD",
                help_text="Devise utilisée pour le prix d'achat",
                max_length=3,
                verbose_name="Devise prix d'achat",
            ),
        ),
    ]
