# Generated by Django 6.0 on 2026-02-06 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0010_company_uses_foreign_currency"),
        ("facture_proforma", "0011_factureproforma_devise_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="factureproforma",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Société propriétaire de la facture pro forma",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="factures_proforma",
                to="company.company",
                verbose_name="Société",
            ),
        ),
        migrations.AddField(
            model_name="historicalfactureproforma",
            name="company",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Société propriétaire de la facture pro forma",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="company.company",
                verbose_name="Société",
            ),
        ),
        migrations.AlterField(
            model_name="factureproforma",
            name="numero_facture",
            field=models.CharField(
                help_text="Format ex: 0001/25",
                max_length=20,
                verbose_name="Numéro de la facture pro forma",
            ),
        ),
        migrations.AlterField(
            model_name="historicalfactureproforma",
            name="numero_facture",
            field=models.CharField(
                help_text="Format ex: 0001/25",
                max_length=20,
                verbose_name="Numéro de la facture pro forma",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="factureproforma",
            unique_together={("numero_facture", "company")},
        ),
    ]
