# Generated by Django 6.0 on 2026-02-06 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facture_proforma", "0012_factureproforma_company_and_more"),
        ("parameter", "0009_alter_historicalcategorie_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factureproforma",
            name="mode_paiement",
            field=models.ForeignKey(
                blank=True,
                help_text="Mode de paiement préféré pour le document",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="parameter.modepaiement",
                verbose_name="Mode de paiement",
            ),
        ),
    ]
