# Generated by Django 6.0.2 on 2026-02-16 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0013_alter_client_company"),
        ("company", "0010_company_uses_foreign_currency"),
        ("facture_proforma", "0015_alter_factureproforma_devise_and_more"),
        ("parameter", "0010_add_company_to_parameters"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="factureproforma",
            index=models.Index(
                fields=["company", "date_facture"],
                name="facture_pro_company_9d28a1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="factureproforma",
            index=models.Index(
                fields=["client", "company"], name="facture_pro_client__64018a_idx"
            ),
        ),
    ]
