# Generated by Django 6.0.6 on 2026-06-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facture_proforma", "0020_factureproforma_date_echeance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="factureproforma",
            name="termes_paiement",
            field=models.TextField(
                blank=True,
                help_text="Conditions ou termes de paiement de la facture pro forma",
                null=True,
                verbose_name="Termes de paiement",
            ),
        ),
        migrations.AddField(
            model_name="historicalfactureproforma",
            name="termes_paiement",
            field=models.TextField(
                blank=True,
                help_text="Conditions ou termes de paiement de la facture pro forma",
                null=True,
                verbose_name="Termes de paiement",
            ),
        ),
    ]
