# Generated by Django 6.0.6 on 2026-07-09 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devi", "0025_devi_date_echeance_historicaldevi_date_echeance"),
        ("facture_proforma", "0021_factureproforma_termes_paiement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="factureproforma",
            name="source_devis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="converted_proformas",
                to="devi.devi",
                verbose_name="Devis source",
            ),
        ),
        migrations.AddField(
            model_name="historicalfactureproforma",
            name="source_devis",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="devi.devi",
                verbose_name="Devis source",
            ),
        ),
    ]
