# Generated by Django 6.0.3 on 2026-08-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facture_proforma", "0022_factureproforma_source_devis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="factureproforma",
            name="fournisseur",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Fournisseur repris par le dossier logistique",
                max_length=255,
                verbose_name="Fournisseur",
            ),
        ),
        migrations.AddField(
            model_name="historicalfactureproforma",
            name="fournisseur",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Fournisseur repris par le dossier logistique",
                max_length=255,
                verbose_name="Fournisseur",
            ),
        ),
    ]
