# Generated by Django 6.0.6 on 2026-08-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facture_proforma", "0023_factureproforma_fournisseur_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="factureproforma",
            name="fournisseur_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Adresse utilisée pour envoyer les justificatifs de paiement",
                max_length=254,
                verbose_name="E-mail fournisseur",
            ),
        ),
        migrations.AddField(
            model_name="historicalfactureproforma",
            name="fournisseur_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Adresse utilisée pour envoyer les justificatifs de paiement",
                max_length=254,
                verbose_name="E-mail fournisseur",
            ),
        ),
    ]
