# Generated by Django 6.0.3 on 2026-08-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facture_proforma", "0024_factureproforma_fournisseur_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factureproforma",
            name="fournisseur",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Fournisseur interne repris lors des conversions",
                max_length=255,
                verbose_name="Fournisseur",
            ),
        ),
        migrations.AlterField(
            model_name="factureproforma",
            name="fournisseur_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Adresse interne reprise lors des conversions",
                max_length=254,
                verbose_name="E-mail fournisseur",
            ),
        ),
        migrations.AlterField(
            model_name="historicalfactureproforma",
            name="fournisseur",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Fournisseur interne repris lors des conversions",
                max_length=255,
                verbose_name="Fournisseur",
            ),
        ),
        migrations.AlterField(
            model_name="historicalfactureproforma",
            name="fournisseur_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Adresse interne reprise lors des conversions",
                max_length=254,
                verbose_name="E-mail fournisseur",
            ),
        ),
    ]
