# Generated by Django 5.2.8 on 2025-12-03 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("article", "0003_alter_article_type_article"),
        ("client", "0007_alter_client_options"),
        ("parameter", "0004_modepaiement_modereglement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Devi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_devis",
                    models.CharField(
                        help_text="Format ex: 0001/25",
                        max_length=20,
                        unique=True,
                        verbose_name="Numéro du devis",
                    ),
                ),
                (
                    "date_devis",
                    models.DateField(db_index=True, verbose_name="Date du devis"),
                ),
                (
                    "numero_demande_prix_client",
                    models.CharField(
                        max_length=50,
                        verbose_name="Numéro de la demande de prix du client",
                    ),
                ),
                (
                    "remarque",
                    models.TextField(blank=True, null=True, verbose_name="Remarque"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("Brouillon", "Brouillon"),
                            ("Envoyé", "Envoyé"),
                            ("Accepté", "Accepté"),
                            ("Refusé", "Refusé"),
                            ("Annulé", "Annulé"),
                            ("Expiré", "Expiré"),
                        ],
                        default="brouillon",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par l'utilisateur",
                    ),
                ),
                (
                    "mode_paiement",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="parameter.modepaiement",
                        verbose_name="Mode de paiement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Devis",
                "verbose_name_plural": "Devis",
                "ordering": ("-date_created",),
            },
        ),
        migrations.CreateModel(
            name="DeviLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prix_achat",
                    models.PositiveIntegerField(verbose_name="Prix d'achat"),
                ),
                (
                    "prix_vente",
                    models.PositiveIntegerField(verbose_name="Prix de vente"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Quantité"),
                ),
                (
                    "pourcentage_remise",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Pourcentage de remise"
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="article.article",
                        verbose_name="Article",
                    ),
                ),
                (
                    "devis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="devi.devi",
                        verbose_name="Devis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de devis",
                "verbose_name_plural": "Lignes de devis",
            },
        ),
    ]
