# Generated by Django 5.2.8 on 2025-12-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devi",
            name="statut",
            field=models.CharField(
                choices=[
                    ("Brouillon", "Brouillon"),
                    ("Envoyé", "Envoyé"),
                    ("Accepté", "Accepté"),
                    ("Refusé", "Refusé"),
                    ("Annulé", "Annulé"),
                    ("Expiré", "Expiré"),
                ],
                default="Brouillon",
                max_length=10,
                verbose_name="Statut",
            ),
        ),
    ]
