# Generated by Django 6.0 on 2025-12-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devi", "0002_alter_devi_statut"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deviline",
            name="pourcentage_remise",
        ),
        migrations.AddField(
            model_name="devi",
            name="remise_type",
            field=models.CharField(
                choices=[("pourcentage", "Pourcentage"), ("fixe", "Fixe")],
                default="pourcentage",
                help_text="Type de remise appliquée : 'pourcentage' ou 'fixe'",
                max_length=12,
                verbose_name="Type de remise",
            ),
        ),
        migrations.AddField(
            model_name="devi",
            name="total_ht",
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                help_text="Somme des totaux des lignes avant TVA",
                verbose_name="Total HT",
            ),
        ),
        migrations.AddField(
            model_name="devi",
            name="total_ttc",
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                help_text="Total toutes taxes comprises (TTC)",
                verbose_name="Total TTC",
            ),
        ),
        migrations.AddField(
            model_name="devi",
            name="total_ttc_apres_remise",
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                help_text="Total TTC après application de la remise",
                verbose_name="Total TTC après remise",
            ),
        ),
        migrations.AddField(
            model_name="devi",
            name="total_tva",
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                help_text="Montant total de la TVA",
                verbose_name="Total TVA",
            ),
        ),
        migrations.AddField(
            model_name="deviline",
            name="remise",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Valeur après application de la remise",
                verbose_name="Valeur remise",
            ),
        ),
        migrations.AddField(
            model_name="deviline",
            name="remise_type",
            field=models.CharField(
                choices=[("pourcentage", "Pourcentage"), ("fixe", "Fixe")],
                default="pourcentage",
                help_text="Type de remise appliquée : 'Pourcentage' ou 'Fixe'",
                max_length=12,
                verbose_name="Type de remise",
            ),
        ),
        migrations.AlterField(
            model_name="devi",
            name="numero_demande_prix_client",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Numéro de la demande de prix du client",
            ),
        ),
        migrations.AlterField(
            model_name="deviline",
            name="prix_achat",
            field=models.PositiveIntegerField(
                help_text="Prix d'achat unitaire (entier positif, ex: en MAD)",
                verbose_name="Prix d'achat",
            ),
        ),
        migrations.AlterField(
            model_name="deviline",
            name="prix_vente",
            field=models.PositiveIntegerField(
                help_text="Prix de vente unitaire (entier positif, ex: en MAD)",
                verbose_name="Prix de vente",
            ),
        ),
        migrations.AlterField(
            model_name="deviline",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Quantité (entier positif)",
                verbose_name="Quantité",
            ),
        ),
    ]
