# Generated by Django 6.0 on 2025-12-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devi", "0003_remove_deviline_pourcentage_remise_devi_remise_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="devi",
            name="remise",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Valeur de la remise appliquée",
                verbose_name="Valeur remise",
            ),
        ),
    ]
