# Generated by Django 6.0 on 2025-12-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devi", "0005_alter_devi_remise_type_alter_deviline_remise_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devi",
            name="remise_type",
            field=models.CharField(
                choices=[("", ""), ("Pourcentage", "Pourcentage"), ("Fixe", "Fixe")],
                default="",
                help_text="Type de remise appliquée : 'Pourcentage' ou 'Fixe'",
                max_length=12,
                null=True,
                verbose_name="Type de remise",
            ),
        ),
        migrations.AlterField(
            model_name="deviline",
            name="remise_type",
            field=models.CharField(
                choices=[("", ""), ("Pourcentage", "Pourcentage"), ("Fixe", "Fixe")],
                default="",
                help_text="Type de remise appliquée : 'Pourcentage' ou 'Fixe'",
                max_length=12,
                null=True,
                verbose_name="Type de remise",
            ),
        ),
    ]
