# Generated by Django 6.0 on 2025-12-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devi", "0007_alter_devi_remise_type_alter_deviline_remise_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devi",
            name="remise",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Valeur de la remise appliquée",
                max_digits=10,
                verbose_name="Valeur remise",
            ),
        ),
        migrations.AlterField(
            model_name="deviline",
            name="remise",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Valeur de la remise appliquée",
                max_digits=10,
                verbose_name="Valeur remise",
            ),
        ),
    ]
