# Generated by Django 6.0 on 2025-12-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devi", "0008_alter_devi_remise_alter_deviline_remise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviline",
            name="prix_achat",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Prix d'achat unitaire (ex: en MAD)",
                max_digits=10,
                verbose_name="Prix d'achat",
            ),
        ),
        migrations.AlterField(
            model_name="deviline",
            name="prix_vente",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Prix de vente unitaire (ex: en MAD)",
                max_digits=10,
                verbose_name="Prix de vente",
            ),
        ),
    ]
