# Generated by Django 6.0.1 on 2026-01-13 09:18

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0006_historicalarticle"),
        ("client", "0009_historicalclient"),
        ("devi", "0010_alter_devi_total_ht_alter_devi_total_ttc_and_more"),
        ("parameter", "0005_livrepar"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalDevi",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "remarque",
                    models.TextField(blank=True, null=True, verbose_name="Remarque"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("Brouillon", "Brouillon"),
                            ("Envoyé", "Envoyé"),
                            ("Accepté", "Accepté"),
                            ("Refusé", "Refusé"),
                            ("Annulé", "Annulé"),
                            ("Expiré", "Expiré"),
                        ],
                        default="Brouillon",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "total_ht",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        help_text="Somme des totaux des lignes avant TVA",
                        max_digits=10,
                        verbose_name="Total HT",
                    ),
                ),
                (
                    "total_tva",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        help_text="Montant total de la TVA",
                        max_digits=10,
                        verbose_name="Total TVA",
                    ),
                ),
                (
                    "total_ttc",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        help_text="Total toutes taxes comprises (TTC)",
                        max_digits=10,
                        verbose_name="Total TTC",
                    ),
                ),
                (
                    "remise_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("Pourcentage", "Pourcentage"),
                            ("Fixe", "Fixe"),
                        ],
                        default="",
                        help_text="Type de remise appliquée : 'Pourcentage' ou 'Fixe'",
                        max_length=12,
                        null=True,
                        verbose_name="Type de remise",
                    ),
                ),
                (
                    "remise",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Valeur de la remise appliquée",
                        max_digits=10,
                        verbose_name="Valeur remise",
                    ),
                ),
                (
                    "total_ttc_apres_remise",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        help_text="Total TTC après application de la remise",
                        max_digits=10,
                        verbose_name="Total TTC après remise",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "numero_devis",
                    models.CharField(
                        db_index=True,
                        help_text="Format ex: 0001/25",
                        max_length=20,
                        verbose_name="Numéro du devis",
                    ),
                ),
                (
                    "date_devis",
                    models.DateField(db_index=True, verbose_name="Date du devis"),
                ),
                (
                    "numero_demande_prix_client",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Numéro de la demande de prix du client",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="client.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par l'utilisateur",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mode_paiement",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="parameter.modepaiement",
                        verbose_name="Mode de paiement",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Devis",
                "verbose_name_plural": "historical Devis",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDeviLine",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "prix_achat",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prix d'achat unitaire (ex: en MAD)",
                        max_digits=10,
                        verbose_name="Prix d'achat",
                    ),
                ),
                (
                    "prix_vente",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prix de vente unitaire (ex: en MAD)",
                        max_digits=10,
                        verbose_name="Prix de vente",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Quantité (entier positif)",
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "remise_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("Pourcentage", "Pourcentage"),
                            ("Fixe", "Fixe"),
                        ],
                        default="",
                        help_text="Type de remise appliquée : 'Pourcentage' ou 'Fixe'",
                        max_length=12,
                        null=True,
                        verbose_name="Type de remise",
                    ),
                ),
                (
                    "remise",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Valeur de la remise appliquée",
                        max_digits=10,
                        verbose_name="Valeur remise",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="article.article",
                        verbose_name="Article",
                    ),
                ),
                (
                    "devis",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="devi.devi",
                        verbose_name="Devis",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Ligne de devis",
                "verbose_name_plural": "historical Lignes de devis",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
