# Generated by Django 6.0 on 2026-01-26 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0007_alter_article_archived_alter_article_categorie_and_more"),
        ("client", "0010_alter_client_cnss_alter_client_ice_and_more"),
        ("devi", "0012_alter_devi_client_alter_deviline_article"),
        ("parameter", "0008_alter_categorie_nom_alter_emplacement_nom_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="devi",
            name="client",
            field=models.ForeignKey(
                help_text="Client associé au document",
                on_delete=django.db.models.deletion.PROTECT,
                to="client.client",
                verbose_name="Client",
            ),
        ),
        migrations.AlterField(
            model_name="devi",
            name="created_by_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Utilisateur ayant créé le document",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par l'utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="devi",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Horodatage de la création du document",
                verbose_name="Date de création",
            ),
        ),
        migrations.AlterField(
            model_name="devi",
            name="date_devis",
            field=models.DateField(
                db_index=True,
                help_text="Date d'émission du devis",
                verbose_name="Date du devis",
            ),
        ),
        migrations.AlterField(
            model_name="devi",
            name="date_updated",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Horodatage de la dernière modification du document",
                verbose_name="Date de mise à jour",
            ),
        ),
        migrations.AlterField(
            model_name="devi",
            name="mode_paiement",
            field=models.ForeignKey(
                help_text="Mode de paiement préféré pour le document",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="parameter.modepaiement",
                verbose_name="Mode de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="devi",
            name="numero_demande_prix_client",
            field=models.CharField(
                blank=True,
                help_text="Numéro de la demande de prix du client (optionnel)",
                max_length=50,
                null=True,
                verbose_name="Numéro de la demande de prix du client",
            ),
        ),
        migrations.AlterField(
            model_name="devi",
            name="remarque",
            field=models.TextField(
                blank=True,
                help_text="Remarque ou note supplémentaire pour le document",
                null=True,
                verbose_name="Remarque",
            ),
        ),
        migrations.AlterField(
            model_name="devi",
            name="statut",
            field=models.CharField(
                choices=[
                    ("Brouillon", "Brouillon"),
                    ("Envoyé", "Envoyé"),
                    ("Accepté", "Accepté"),
                    ("Refusé", "Refusé"),
                    ("Annulé", "Annulé"),
                    ("Expiré", "Expiré"),
                ],
                default="Brouillon",
                help_text="Statut du document (ex: Brouillon, Envoyé)",
                max_length=10,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="deviline",
            name="article",
            field=models.ForeignKey(
                help_text="Article associé à cette ligne de devis",
                on_delete=django.db.models.deletion.PROTECT,
                to="article.article",
                verbose_name="Article",
            ),
        ),
        migrations.AlterField(
            model_name="deviline",
            name="devis",
            field=models.ForeignKey(
                help_text="Document Devis parent associé à cette ligne",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lignes",
                to="devi.devi",
                verbose_name="Devis",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldevi",
            name="client",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Client associé au document",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="client.client",
                verbose_name="Client",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldevi",
            name="created_by_user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Utilisateur ayant créé le document",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par l'utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldevi",
            name="date_created",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Horodatage de la création du document",
                verbose_name="Date de création",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldevi",
            name="date_devis",
            field=models.DateField(
                db_index=True,
                help_text="Date d'émission du devis",
                verbose_name="Date du devis",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldevi",
            name="date_updated",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Horodatage de la dernière modification du document",
                verbose_name="Date de mise à jour",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldevi",
            name="mode_paiement",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Mode de paiement préféré pour le document",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="parameter.modepaiement",
                verbose_name="Mode de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldevi",
            name="numero_demande_prix_client",
            field=models.CharField(
                blank=True,
                help_text="Numéro de la demande de prix du client (optionnel)",
                max_length=50,
                null=True,
                verbose_name="Numéro de la demande de prix du client",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldevi",
            name="remarque",
            field=models.TextField(
                blank=True,
                help_text="Remarque ou note supplémentaire pour le document",
                null=True,
                verbose_name="Remarque",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldevi",
            name="statut",
            field=models.CharField(
                choices=[
                    ("Brouillon", "Brouillon"),
                    ("Envoyé", "Envoyé"),
                    ("Accepté", "Accepté"),
                    ("Refusé", "Refusé"),
                    ("Annulé", "Annulé"),
                    ("Expiré", "Expiré"),
                ],
                default="Brouillon",
                help_text="Statut du document (ex: Brouillon, Envoyé)",
                max_length=10,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldeviline",
            name="article",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Article associé à cette ligne de devis",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="article.article",
                verbose_name="Article",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldeviline",
            name="devis",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Document Devis parent associé à cette ligne",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="devi.devi",
                verbose_name="Devis",
            ),
        ),
    ]
