# Generated by Django 6.0 on 2026-01-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devi", "0013_alter_devi_client_alter_devi_created_by_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicaldevi",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "Historique Devis",
                "verbose_name_plural": "Historiques Devis",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaldeviline",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "Historique Ligne de devis",
                "verbose_name_plural": "Historiques Lignes de devis",
            },
        ),
    ]
