# Generated by Django 6.0 on 2026-02-06 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0010_company_uses_foreign_currency"),
        ("devi", "0016_devi_devise_deviline_devise_prix_vente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="devi",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Société propriétaire du devis",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devis",
                to="company.company",
                verbose_name="Société",
            ),
        ),
        migrations.AddField(
            model_name="historicaldevi",
            name="company",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Société propriétaire du devis",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="company.company",
                verbose_name="Société",
            ),
        ),
        migrations.AlterField(
            model_name="devi",
            name="numero_devis",
            field=models.CharField(
                help_text="Format ex: 0001/25",
                max_length=20,
                verbose_name="Numéro du devis",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldevi",
            name="numero_devis",
            field=models.CharField(
                help_text="Format ex: 0001/25",
                max_length=20,
                verbose_name="Numéro du devis",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="devi",
            unique_together={("numero_devis", "company")},
        ),
    ]
