# Generated by Django 6.0 on 2026-02-06 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0010_company_uses_foreign_currency"),
        ("devi", "0018_alter_devi_mode_paiement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devi",
            name="company",
            field=models.ForeignKey(
                help_text="Société propriétaire du devis",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devis",
                to="company.company",
                verbose_name="Société",
            ),
        ),
    ]
