# Generated by Django 6.0 on 2026-02-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devi", "0019_alter_devi_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devi",
            name="devise",
            field=models.CharField(
                choices=[
                    ("MAD", "MAD – Dirham Marocain"),
                    ("EUR", "EUR – Euro"),
                    ("USD", "USD – Dollar Américain"),
                ],
                db_index=True,
                default="MAD",
                help_text="Devise utilisée pour ce document (héritée du premier article ajouté)",
                max_length=3,
                verbose_name="Devise",
            ),
        ),
        migrations.AlterField(
            model_name="devi",
            name="statut",
            field=models.CharField(
                choices=[
                    ("Brouillon", "Brouillon"),
                    ("Envoyé", "Envoyé"),
                    ("Accepté", "Accepté"),
                    ("Refusé", "Refusé"),
                    ("Annulé", "Annulé"),
                    ("Expiré", "Expiré"),
                ],
                db_index=True,
                default="Brouillon",
                help_text="Statut du document (ex: Brouillon, Envoyé)",
                max_length=10,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldevi",
            name="devise",
            field=models.CharField(
                choices=[
                    ("MAD", "MAD – Dirham Marocain"),
                    ("EUR", "EUR – Euro"),
                    ("USD", "USD – Dollar Américain"),
                ],
                db_index=True,
                default="MAD",
                help_text="Devise utilisée pour ce document (héritée du premier article ajouté)",
                max_length=3,
                verbose_name="Devise",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldevi",
            name="statut",
            field=models.CharField(
                choices=[
                    ("Brouillon", "Brouillon"),
                    ("Envoyé", "Envoyé"),
                    ("Accepté", "Accepté"),
                    ("Refusé", "Refusé"),
                    ("Annulé", "Annulé"),
                    ("Expiré", "Expiré"),
                ],
                db_index=True,
                default="Brouillon",
                help_text="Statut du document (ex: Brouillon, Envoyé)",
                max_length=10,
                verbose_name="Statut",
            ),
        ),
    ]
