# Generated by Django 6.0.2 on 2026-02-16 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0013_alter_client_company"),
        ("company", "0010_company_uses_foreign_currency"),
        ("devi", "0020_alter_devi_devise_alter_devi_statut_and_more"),
        ("parameter", "0010_add_company_to_parameters"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="devi",
            index=models.Index(
                fields=["company", "date_devis"], name="devi_devi_company_5ff77b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="devi",
            index=models.Index(
                fields=["client", "company"], name="devi_devi_client__cf3348_idx"
            ),
        ),
    ]
