# Generated by Django 6.0.2 on 2026-02-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devi", "0021_devi_devi_devi_company_5ff77b_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviline",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Quantité (ex: 15,35)",
                max_digits=10,
                verbose_name="Quantité",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldeviline",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Quantité (ex: 15,35)",
                max_digits=10,
                verbose_name="Quantité",
            ),
        ),
    ]
