# Generated by Django 6.0.3 on 2026-08-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devi", "0025_devi_date_echeance_historicaldevi_date_echeance"),
    ]

    operations = [
        migrations.AddField(
            model_name="devi",
            name="fournisseur",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Fournisseur interne repris lors des conversions",
                max_length=255,
                verbose_name="Fournisseur",
            ),
        ),
        migrations.AddField(
            model_name="devi",
            name="fournisseur_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Adresse interne reprise lors des conversions",
                max_length=254,
                verbose_name="E-mail fournisseur",
            ),
        ),
        migrations.AddField(
            model_name="historicaldevi",
            name="fournisseur",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Fournisseur interne repris lors des conversions",
                max_length=255,
                verbose_name="Fournisseur",
            ),
        ),
        migrations.AddField(
            model_name="historicaldevi",
            name="fournisseur_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Adresse interne reprise lors des conversions",
                max_length=254,
                verbose_name="E-mail fournisseur",
            ),
        ),
    ]
