# Generated by Django 5.2.7 on 2025-11-07 15:43

import company.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raison_sociale",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Raison sociale"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default=None,
                        max_length=254,
                        null=True,
                        verbose_name="E‑mail",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=company.models.get_company_image_path,
                        verbose_name="Logo",
                    ),
                ),
                (
                    "cachet",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=company.models.get_company_image_path,
                        verbose_name="Cachet",
                    ),
                ),
                (
                    "nbr_employe",
                    models.CharField(
                        choices=[
                            ("1 à 5", "1 à 5"),
                            ("5 à 10", "5 à 10"),
                            ("10 à 50", "10 à 50"),
                            ("50 à 100", "50 à 100"),
                            ("plus que 100", "plus que 100"),
                        ],
                        default=1,
                        max_length=12,
                        verbose_name="Nombre d'employés",
                    ),
                ),
                (
                    "civilite_responsable",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("Mme", "Mme"),
                            ("Mlle", "Mlle"),
                            ("M.", "M."),
                        ],
                        default="",
                        max_length=4,
                        null=True,
                        verbose_name="Civilité du responsable",
                    ),
                ),
                (
                    "nom_responsable",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="Nom du responsable",
                    ),
                ),
                (
                    "gsm_responsable",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Tapez un numéro de téléphone valide",
                                regex="^\\+?\\d{7,15}$",
                            )
                        ],
                        verbose_name="GSM du responsable",
                    ),
                ),
                (
                    "adresse",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Adresse"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Tapez un numéro de téléphone valide",
                                regex="^\\+?\\d{7,15}$",
                            )
                        ],
                        verbose_name="Téléphone",
                    ),
                ),
                (
                    "fax",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Tapez un numéro de téléphone valide",
                                regex="^\\+?\\d{7,15}$",
                            )
                        ],
                        verbose_name="Fax",
                    ),
                ),
                (
                    "site_web",
                    models.URLField(
                        blank=True, default="", null=True, verbose_name="Site web"
                    ),
                ),
                (
                    "numero_du_compte",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="Numéro du compte",
                    ),
                ),
                (
                    "ICE",
                    models.CharField(max_length=100, unique=True, verbose_name="ICE"),
                ),
                (
                    "registre_de_commerce",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="Registre de commerce",
                    ),
                ),
                (
                    "identifiant_fiscal",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="Identifiant fiscal",
                    ),
                ),
                (
                    "tax_professionnelle",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="Taxe professionnelle",
                    ),
                ),
                (
                    "CNSS",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="CNSS",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "ordering": ("raison_sociale",),
            },
        ),
    ]
