# Generated by Django 5.2.8 on 2025-11-10 10:08

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="cachet_cropped",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to=company.models.get_company_image_path,
                verbose_name="Cachet cropped",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="logo_cropped",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to=company.models.get_company_image_path,
                verbose_name="Logo cropped",
            ),
        ),
    ]
