# Generated by Django 5.2.8 on 2025-11-10 10:16

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_company_cachet_cropped_company_logo_cropped"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="cachet",
            field=models.ImageField(
                blank=True,
                default=None,
                max_length=1000,
                null=True,
                upload_to=company.models.get_company_image_path,
                verbose_name="Cachet",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="cachet_cropped",
            field=models.ImageField(
                blank=True,
                default=None,
                max_length=1000,
                null=True,
                upload_to=company.models.get_company_image_path,
                verbose_name="Cachet cropped",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.ImageField(
                blank=True,
                default=None,
                max_length=1000,
                null=True,
                upload_to=company.models.get_company_image_path,
                verbose_name="Logo",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="logo_cropped",
            field=models.ImageField(
                blank=True,
                default=None,
                max_length=1000,
                null=True,
                upload_to=company.models.get_company_image_path,
                verbose_name="Logo cropped",
            ),
        ),
    ]
