# Generated by Django 5.2.8 on 2025-11-27 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_alter_company_cachet_alter_company_cachet_cropped_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="civilite_responsable",
            field=models.CharField(
                choices=[("", ""), ("Mme", "Mme"), ("Mlle", "Mlle"), ("M.", "M.")],
                default="",
                max_length=4,
                verbose_name="Civilité du responsable",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="date_created",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="raison_sociale",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, verbose_name="Raison sociale"
            ),
        ),
    ]
