# Generated by Django 5.2.8 on 2025-11-27 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_alter_company_civilite_responsable_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ("-date_created",),
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
    ]
