# Generated by Django 6.0.1 on 2026-01-13 09:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0006_company_date_updated"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="suspended",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Suspendu"
            ),
        ),
        migrations.CreateModel(
            name="HistoricalCompany",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "raison_sociale",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        verbose_name="Raison sociale",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default=None,
                        max_length=254,
                        null=True,
                        verbose_name="E‑mail",
                    ),
                ),
                (
                    "logo",
                    models.TextField(
                        blank=True,
                        default=None,
                        max_length=1000,
                        null=True,
                        verbose_name="Logo",
                    ),
                ),
                (
                    "logo_cropped",
                    models.TextField(
                        blank=True,
                        default=None,
                        max_length=1000,
                        null=True,
                        verbose_name="Logo cropped",
                    ),
                ),
                (
                    "cachet",
                    models.TextField(
                        blank=True,
                        default=None,
                        max_length=1000,
                        null=True,
                        verbose_name="Cachet",
                    ),
                ),
                (
                    "cachet_cropped",
                    models.TextField(
                        blank=True,
                        default=None,
                        max_length=1000,
                        null=True,
                        verbose_name="Cachet cropped",
                    ),
                ),
                (
                    "nbr_employe",
                    models.CharField(
                        choices=[
                            ("1 à 5", "1 à 5"),
                            ("5 à 10", "5 à 10"),
                            ("10 à 50", "10 à 50"),
                            ("50 à 100", "50 à 100"),
                            ("plus que 100", "plus que 100"),
                        ],
                        default=1,
                        max_length=12,
                        verbose_name="Nombre d'employés",
                    ),
                ),
                (
                    "civilite_responsable",
                    models.CharField(
                        choices=[
                            ("", ""),
                            ("Mme", "Mme"),
                            ("Mlle", "Mlle"),
                            ("M.", "M."),
                        ],
                        default="",
                        max_length=4,
                        verbose_name="Civilité du responsable",
                    ),
                ),
                (
                    "nom_responsable",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="Nom du responsable",
                    ),
                ),
                (
                    "gsm_responsable",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Tapez un numéro de téléphone valide",
                                regex="^\\+?\\d{7,15}$",
                            )
                        ],
                        verbose_name="GSM du responsable",
                    ),
                ),
                (
                    "adresse",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Adresse"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Tapez un numéro de téléphone valide",
                                regex="^\\+?\\d{7,15}$",
                            )
                        ],
                        verbose_name="Téléphone",
                    ),
                ),
                (
                    "fax",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Tapez un numéro de téléphone valide",
                                regex="^\\+?\\d{7,15}$",
                            )
                        ],
                        verbose_name="Fax",
                    ),
                ),
                (
                    "site_web",
                    models.URLField(
                        blank=True, default="", null=True, verbose_name="Site web"
                    ),
                ),
                (
                    "numero_du_compte",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="Numéro du compte",
                    ),
                ),
                (
                    "ICE",
                    models.CharField(db_index=True, max_length=100, verbose_name="ICE"),
                ),
                (
                    "registre_de_commerce",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="Registre de commerce",
                    ),
                ),
                (
                    "identifiant_fiscal",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="Identifiant fiscal",
                    ),
                ),
                (
                    "tax_professionnelle",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="Taxe professionnelle",
                    ),
                ),
                (
                    "CNSS",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="CNSS",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        verbose_name="Date de modification",
                    ),
                ),
                (
                    "suspended",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Suspendu"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Company",
                "verbose_name_plural": "historical Companies",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
