# Generated by Django 6.0 on 2026-01-26 11:11

import company.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0007_company_suspended_historicalcompany"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ("-date_created",),
                "verbose_name": "Société",
                "verbose_name_plural": "Sociétés",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcompany",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Société",
                "verbose_name_plural": "historical Sociétés",
            },
        ),
        migrations.AlterField(
            model_name="company",
            name="CNSS",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Numéro CNSS de l'entreprise",
                max_length=100,
                null=True,
                verbose_name="CNSS",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="ICE",
            field=models.CharField(
                help_text="Identifiant Commun de l'Entreprise (ICE)",
                max_length=100,
                unique=True,
                verbose_name="ICE",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="adresse",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Adresse postale complète de l'entreprise",
                null=True,
                verbose_name="Adresse",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="cachet",
            field=models.ImageField(
                blank=True,
                default=None,
                help_text="Image du cachet de l'entreprise",
                max_length=1000,
                null=True,
                upload_to=company.models.get_company_image_path,
                verbose_name="Cachet",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="cachet_cropped",
            field=models.ImageField(
                blank=True,
                default=None,
                help_text="Version recadrée du cachet",
                max_length=1000,
                null=True,
                upload_to=company.models.get_company_image_path,
                verbose_name="Cachet recadré",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="civilite_responsable",
            field=models.CharField(
                choices=[("", ""), ("Mme", "Mme"), ("Mlle", "Mlle"), ("M.", "M.")],
                default="",
                help_text="Civilité du responsable (Mme, M., ...)",
                max_length=4,
                verbose_name="Civilité du responsable",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="date_created",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="Horodatage de la création de l'enregistrement",
                verbose_name="Date de création",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="date_updated",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Horodatage de la dernière modification",
                verbose_name="Date de modification",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.EmailField(
                blank=True,
                default=None,
                help_text="Adresse e‑mail de contact de l'entreprise",
                max_length=254,
                null=True,
                verbose_name="E‑mail",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="fax",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Numéro de fax (optionnel)",
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Tapez un numéro de téléphone valide",
                        regex="^\\+?\\d{7,15}$",
                    )
                ],
                verbose_name="Fax",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="gsm_responsable",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Numéro mobile du responsable (format international recommandé)",
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Tapez un numéro de téléphone valide",
                        regex="^\\+?\\d{7,15}$",
                    )
                ],
                verbose_name="GSM du responsable",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="identifiant_fiscal",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Identifiant fiscal de l'entreprise",
                max_length=100,
                null=True,
                verbose_name="Identifiant fiscal",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.ImageField(
                blank=True,
                default=None,
                help_text="Logo de l'entreprise (image)",
                max_length=1000,
                null=True,
                upload_to=company.models.get_company_image_path,
                verbose_name="Logo",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="logo_cropped",
            field=models.ImageField(
                blank=True,
                default=None,
                help_text="Version recadrée du logo",
                max_length=1000,
                null=True,
                upload_to=company.models.get_company_image_path,
                verbose_name="Logo recadré",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="nbr_employe",
            field=models.CharField(
                choices=[
                    ("1 à 5", "1 à 5"),
                    ("5 à 10", "5 à 10"),
                    ("10 à 50", "10 à 50"),
                    ("50 à 100", "50 à 100"),
                    ("plus que 100", "plus que 100"),
                ],
                default=1,
                help_text="Tranche du nombre d'employés",
                max_length=12,
                verbose_name="Nombre d'employés",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="nom_responsable",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Nom complet du responsable",
                max_length=255,
                null=True,
                verbose_name="Nom du responsable",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="numero_du_compte",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Numéro de compte bancaire ou interne",
                max_length=100,
                null=True,
                verbose_name="Numéro du compte",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="raison_sociale",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Raison sociale de l'entreprise",
                max_length=255,
                verbose_name="Raison sociale",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="registre_de_commerce",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Numéro du registre de commerce",
                max_length=100,
                null=True,
                verbose_name="Registre de commerce",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="site_web",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL du site web de l'entreprise",
                null=True,
                verbose_name="Site web",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="suspended",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indique si l'entreprise est suspendue",
                verbose_name="Suspendu",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="tax_professionnelle",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Numéro / référence de la taxe professionnelle",
                max_length=100,
                null=True,
                verbose_name="Taxe professionnelle",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="telephone",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Numéro de téléphone principal",
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Tapez un numéro de téléphone valide",
                        regex="^\\+?\\d{7,15}$",
                    )
                ],
                verbose_name="Téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompany",
            name="CNSS",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Numéro CNSS de l'entreprise",
                max_length=100,
                null=True,
                verbose_name="CNSS",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompany",
            name="ICE",
            field=models.CharField(
                db_index=True,
                help_text="Identifiant Commun de l'Entreprise (ICE)",
                max_length=100,
                verbose_name="ICE",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompany",
            name="adresse",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Adresse postale complète de l'entreprise",
                null=True,
                verbose_name="Adresse",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompany",
            name="cachet",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Image du cachet de l'entreprise",
                max_length=1000,
                null=True,
                verbose_name="Cachet",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompany",
            name="cachet_cropped",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Version recadrée du cachet",
                max_length=1000,
                null=True,
                verbose_name="Cachet recadré",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompany",
            name="civilite_responsable",
            field=models.CharField(
                choices=[("", ""), ("Mme", "Mme"), ("Mlle", "Mlle"), ("M.", "M.")],
                default="",
                help_text="Civilité du responsable (Mme, M., ...)",
                max_length=4,
                verbose_name="Civilité du responsable",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompany",
            name="date_created",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="Horodatage de la création de l'enregistrement",
                verbose_name="Date de création",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompany",
            name="date_updated",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Horodatage de la dernière modification",
                verbose_name="Date de modification",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompany",
            name="email",
            field=models.EmailField(
                blank=True,
                default=None,
                help_text="Adresse e‑mail de contact de l'entreprise",
                max_length=254,
                null=True,
                verbose_name="E‑mail",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompany",
            name="fax",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Numéro de fax (optionnel)",
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Tapez un numéro de téléphone valide",
                        regex="^\\+?\\d{7,15}$",
                    )
                ],
                verbose_name="Fax",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompany",
            name="gsm_responsable",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Numéro mobile du responsable (format international recommandé)",
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Tapez un numéro de téléphone valide",
                        regex="^\\+?\\d{7,15}$",
                    )
                ],
                verbose_name="GSM du responsable",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompany",
            name="identifiant_fiscal",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Identifiant fiscal de l'entreprise",
                max_length=100,
                null=True,
                verbose_name="Identifiant fiscal",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompany",
            name="logo",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Logo de l'entreprise (image)",
                max_length=1000,
                null=True,
                verbose_name="Logo",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompany",
            name="logo_cropped",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Version recadrée du logo",
                max_length=1000,
                null=True,
                verbose_name="Logo recadré",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompany",
            name="nbr_employe",
            field=models.CharField(
                choices=[
                    ("1 à 5", "1 à 5"),
                    ("5 à 10", "5 à 10"),
                    ("10 à 50", "10 à 50"),
                    ("50 à 100", "50 à 100"),
                    ("plus que 100", "plus que 100"),
                ],
                default=1,
                help_text="Tranche du nombre d'employés",
                max_length=12,
                verbose_name="Nombre d'employés",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompany",
            name="nom_responsable",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Nom complet du responsable",
                max_length=255,
                null=True,
                verbose_name="Nom du responsable",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompany",
            name="numero_du_compte",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Numéro de compte bancaire ou interne",
                max_length=100,
                null=True,
                verbose_name="Numéro du compte",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompany",
            name="raison_sociale",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Raison sociale de l'entreprise",
                max_length=255,
                verbose_name="Raison sociale",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompany",
            name="registre_de_commerce",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Numéro du registre de commerce",
                max_length=100,
                null=True,
                verbose_name="Registre de commerce",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompany",
            name="site_web",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL du site web de l'entreprise",
                null=True,
                verbose_name="Site web",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompany",
            name="suspended",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indique si l'entreprise est suspendue",
                verbose_name="Suspendu",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompany",
            name="tax_professionnelle",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Numéro / référence de la taxe professionnelle",
                max_length=100,
                null=True,
                verbose_name="Taxe professionnelle",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompany",
            name="telephone",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Numéro de téléphone principal",
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Tapez un numéro de téléphone valide",
                        regex="^\\+?\\d{7,15}$",
                    )
                ],
                verbose_name="Téléphone",
            ),
        ),
    ]
