# Generated by Django 6.0 on 2026-01-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0008_alter_company_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalcompany",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "Historique Société",
                "verbose_name_plural": "Historiques Sociétés",
            },
        ),
    ]
