# Generated by Django 6.0.1 on 2026-02-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0009_alter_historicalcompany_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="uses_foreign_currency",
            field=models.BooleanField(
                default=False,
                help_text="Si activé, les sélecteurs de devise sont affichés dans les articles et les documents",
                verbose_name="Utilise une devise étrangère",
            ),
        ),
        migrations.AddField(
            model_name="historicalcompany",
            name="uses_foreign_currency",
            field=models.BooleanField(
                default=False,
                help_text="Si activé, les sélecteurs de devise sont affichés dans les articles et les documents",
                verbose_name="Utilise une devise étrangère",
            ),
        ),
    ]
