# Generated by Django 6.1.1 on 2026-09-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0010_company_uses_foreign_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="stock_management_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Active les réservations, les entrées et les sorties de stock pour cette société",
                verbose_name="Gestion de stock activée",
            ),
        ),
        migrations.AddField(
            model_name="historicalcompany",
            name="stock_management_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Active les réservations, les entrées et les sorties de stock pour cette société",
                verbose_name="Gestion de stock activée",
            ),
        ),
    ]
