# Generated by Django 6.1.1 on 2026-10-07 10:55

from django.db import migrations, models


def preserve_existing_inventories(apps, schema_editor):
    alias = schema_editor.connection.alias
    company_ids = (
        apps.get_model("stock", "InventorySession")
        .objects.using(alias)
        .values("company_id")
    )
    apps.get_model("company", "Company").objects.using(alias).filter(
        pk__in=company_ids, stock_management_enabled=True
    ).update(inventory_management_enabled=True)


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0011_company_stock_management_enabled_and_more"),
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="inventory_management_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Autorise le comptage et la régularisation du stock par inventaire",
                verbose_name="Inventaire activé",
            ),
        ),
        migrations.AddField(
            model_name="historicalcompany",
            name="inventory_management_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Autorise le comptage et la régularisation du stock par inventaire",
                verbose_name="Inventaire activé",
            ),
        ),
        migrations.RunPython(preserve_existing_inventories, migrations.RunPython.noop),
    ]
