# Generated by Django 6.1.1 on 2026-10-07 11:05

from django.db import migrations, models


def normalize_legacy_default(apps, schema_editor):
    apps.get_model("company", "Company").objects.using(
        schema_editor.connection.alias
    ).filter(nbr_employe="1").update(nbr_employe="1 à 5")


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0012_company_inventory_management_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="nbr_employe",
            field=models.CharField(
                choices=[
                    ("1 à 5", "1 à 5"),
                    ("5 à 10", "5 à 10"),
                    ("10 à 50", "10 à 50"),
                    ("50 à 100", "50 à 100"),
                    ("plus que 100", "plus que 100"),
                ],
                default="1 à 5",
                help_text="Tranche du nombre d'employés",
                max_length=12,
                verbose_name="Nombre d'employés",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompany",
            name="nbr_employe",
            field=models.CharField(
                choices=[
                    ("1 à 5", "1 à 5"),
                    ("5 à 10", "5 à 10"),
                    ("10 à 50", "10 à 50"),
                    ("50 à 100", "50 à 100"),
                    ("plus que 100", "plus que 100"),
                ],
                default="1 à 5",
                help_text="Tranche du nombre d'employés",
                max_length=12,
                verbose_name="Nombre d'employés",
            ),
        ),
        migrations.RunPython(normalize_legacy_default, migrations.RunPython.noop),
    ]
