# Generated by Django 5.2.8 on 2025-11-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parameter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ville",
            name="nom",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Nom de la ville"
            ),
        ),
    ]
