# Generated by Django 5.2.8 on 2025-11-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parameter", "0002_alter_ville_nom"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Nom de la catégorie"
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
            },
        ),
        migrations.CreateModel(
            name="Emplacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Nom de l'emplacement"
                    ),
                ),
            ],
            options={
                "verbose_name": "Emplacement",
                "verbose_name_plural": "Emplacements",
            },
        ),
        migrations.CreateModel(
            name="Marque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Nom de la marque"
                    ),
                ),
            ],
            options={
                "verbose_name": "Marque",
                "verbose_name_plural": "Marques",
            },
        ),
        migrations.CreateModel(
            name="Unite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Nom de l'unité"
                    ),
                ),
            ],
            options={
                "verbose_name": "Unité",
                "verbose_name_plural": "Unités",
            },
        ),
    ]
