# Generated by Django 5.2.8 on 2025-12-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parameter", "0003_categorie_emplacement_marque_unite"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModePaiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Nom du mode de paiement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mode de paiement",
                "verbose_name_plural": "Modes de paiement",
            },
        ),
        migrations.CreateModel(
            name="ModeReglement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Nom du mode de règlement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mode de règlement",
                "verbose_name_plural": "Modes de règlement",
            },
        ),
    ]
