# Generated by Django 6.0 on 2025-12-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parameter", "0004_modepaiement_modereglement"),
    ]

    operations = [
        migrations.CreateModel(
            name="LivrePar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Nom du livreur"
                    ),
                ),
            ],
            options={
                "verbose_name": "Livré par",
                "verbose_name_plural": "Livré par",
            },
        ),
    ]
