# Generated by Django 6.0.1 on 2026-01-13 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parameter", "0005_livrepar"),
        ("reglement", "0002_alter_reglement_mode_reglement_historicalreglement"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ModeReglement",
        ),
    ]
