# Generated by Django 6.0 on 2026-01-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parameter", "0007_historicalcategorie_historicalemplacement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorie",
            name="nom",
            field=models.CharField(
                help_text="Nom unique de la catégorie",
                max_length=255,
                unique=True,
                verbose_name="Nom de la catégorie",
            ),
        ),
        migrations.AlterField(
            model_name="emplacement",
            name="nom",
            field=models.CharField(
                help_text="Nom unique de l'emplacement (ex: Entrepôt A)",
                max_length=255,
                unique=True,
                verbose_name="Nom de l'emplacement",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcategorie",
            name="nom",
            field=models.CharField(
                db_index=True,
                help_text="Nom unique de la catégorie",
                max_length=255,
                verbose_name="Nom de la catégorie",
            ),
        ),
        migrations.AlterField(
            model_name="historicalemplacement",
            name="nom",
            field=models.CharField(
                db_index=True,
                help_text="Nom unique de l'emplacement (ex: Entrepôt A)",
                max_length=255,
                verbose_name="Nom de l'emplacement",
            ),
        ),
        migrations.AlterField(
            model_name="historicallivrepar",
            name="nom",
            field=models.CharField(
                db_index=True,
                help_text="Nom unique du livreur",
                max_length=255,
                verbose_name="Nom du livreur",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmarque",
            name="nom",
            field=models.CharField(
                db_index=True,
                help_text="Nom unique de la marque",
                max_length=255,
                verbose_name="Nom de la marque",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmodepaiement",
            name="nom",
            field=models.CharField(
                db_index=True,
                help_text="Nom unique du mode de paiement (ex: Espèces, Virement)",
                max_length=255,
                verbose_name="Nom du mode de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="historicalunite",
            name="nom",
            field=models.CharField(
                db_index=True,
                help_text="Nom unique de l'unité (ex: pièce, kg)",
                max_length=255,
                verbose_name="Nom de l'unité",
            ),
        ),
        migrations.AlterField(
            model_name="historicalville",
            name="nom",
            field=models.CharField(
                db_index=True,
                help_text="Nom unique de la ville",
                max_length=100,
                verbose_name="Nom de la ville",
            ),
        ),
        migrations.AlterField(
            model_name="livrepar",
            name="nom",
            field=models.CharField(
                help_text="Nom unique du livreur",
                max_length=255,
                unique=True,
                verbose_name="Nom du livreur",
            ),
        ),
        migrations.AlterField(
            model_name="marque",
            name="nom",
            field=models.CharField(
                help_text="Nom unique de la marque",
                max_length=255,
                unique=True,
                verbose_name="Nom de la marque",
            ),
        ),
        migrations.AlterField(
            model_name="modepaiement",
            name="nom",
            field=models.CharField(
                help_text="Nom unique du mode de paiement (ex: Espèces, Virement)",
                max_length=255,
                unique=True,
                verbose_name="Nom du mode de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="unite",
            name="nom",
            field=models.CharField(
                help_text="Nom unique de l'unité (ex: pièce, kg)",
                max_length=255,
                unique=True,
                verbose_name="Nom de l'unité",
            ),
        ),
        migrations.AlterField(
            model_name="ville",
            name="nom",
            field=models.CharField(
                help_text="Nom unique de la ville",
                max_length=100,
                unique=True,
                verbose_name="Nom de la ville",
            ),
        ),
    ]
