# Generated by Django 6.0 on 2026-01-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parameter", "0008_alter_categorie_nom_alter_emplacement_nom_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalcategorie",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "Historique Catégorie",
                "verbose_name_plural": "Historiques Catégories",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalemplacement",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "Historique Emplacement",
                "verbose_name_plural": "Historiques Emplacements",
            },
        ),
        migrations.AlterModelOptions(
            name="historicallivrepar",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "Historique Livré par",
                "verbose_name_plural": "Historiques Livré par",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalmarque",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "Historique Marque",
                "verbose_name_plural": "Historiques Marques",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalmodepaiement",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "Historique Mode de paiement",
                "verbose_name_plural": "Historiques Modes de paiement",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalunite",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "Historique Unité",
                "verbose_name_plural": "Historiques Unités",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalville",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "Historique Ville",
                "verbose_name_plural": "Historiques Villes",
            },
        ),
    ]
