from django.urls import path

from .views import (
    BulkDeleteLogisticsOrderView,
    GenerateNumeroLogistiqueView,
    LogisticsDashboardView,
    LogisticsOrderDetailEditDeleteView,
    LogisticsOrderListCreateView,
    LogisticsOrderSourcePreviewView,
    LogisticsResponsibleOptionsView,
    LogisticsOrderStatusUpdateView,
    LogisticsOrderGlobalStatusUpdateView,
    LogisticsPaymentRejectView,
    LogisticsPaymentEmailRetryView,
    LogisticsPaymentRequestView,
    LogisticsPaymentStartView,
    LogisticsPaymentExecutionView,
    LogisticsPaymentReceiptConfirmView,
    LogisticsPaymentValidateView,
    LogisticsLaunchStatusUpdateView,
    LogisticsProformaRequestView,
    LogisticsSupplierProformaReviewView,
    LogisticsSwiftSentView,
)

app_name = "logistique"

urlpatterns = [
    path("", LogisticsOrderListCreateView.as_view(), name="logistique-list-create"),
    path(
        "source_preview/",
        LogisticsOrderSourcePreviewView.as_view(),
        name="logistique-source-preview",
    ),
    path("dashboard/", LogisticsDashboardView.as_view(), name="logistique-dashboard"),
    path(
        "bulk_delete/",
        BulkDeleteLogisticsOrderView.as_view(),
        name="logistique-bulk-delete",
    ),
    path(
        "generate_num_commande/",
        GenerateNumeroLogistiqueView.as_view(),
        name="generate-numero-logistique",
    ),
    path(
        "responsables/",
        LogisticsResponsibleOptionsView.as_view(),
        name="logistique-responsables",
    ),
    path(
        "<int:pk>/",
        LogisticsOrderDetailEditDeleteView.as_view(),
        name="logistique-detail",
    ),
    path(
        "switch_statut/<int:pk>/",
        LogisticsOrderStatusUpdateView.as_view(),
        name="logistique-statut-update",
    ),
    path(
        "switch_global_status/<int:pk>/",
        LogisticsOrderGlobalStatusUpdateView.as_view(),
        name="logistique-global-status-update",
    ),
    path(
        "<int:pk>/record_proforma_request/",
        LogisticsProformaRequestView.as_view(),
        name="logistique-record-proforma-request",
    ),
    path(
        "<int:pk>/launch_status/",
        LogisticsLaunchStatusUpdateView.as_view(),
        name="logistique-launch-status-update",
    ),
    path(
        "<int:pk>/review_supplier_proforma/",
        LogisticsSupplierProformaReviewView.as_view(),
        name="logistique-review-supplier-proforma",
    ),
    path(
        "<int:pk>/request_payment/",
        LogisticsPaymentRequestView.as_view(),
        name="logistique-request-payment",
    ),
    path(
        "<int:pk>/retry_payment_email/",
        LogisticsPaymentEmailRetryView.as_view(),
        name="logistique-retry-payment-email",
    ),
    path(
        "<int:pk>/start_payment/",
        LogisticsPaymentStartView.as_view(),
        name="logistique-start-payment",
    ),
    path(
        "<int:pk>/record_payment_execution/",
        LogisticsPaymentExecutionView.as_view(),
        name="logistique-record-payment-execution",
    ),
    path(
        "<int:pk>/validate_payment/",
        LogisticsPaymentValidateView.as_view(),
        name="logistique-validate-payment",
    ),
    path(
        "<int:pk>/reject_payment/",
        LogisticsPaymentRejectView.as_view(),
        name="logistique-reject-payment",
    ),
    path(
        "<int:pk>/send_swift/",
        LogisticsSwiftSentView.as_view(),
        name="logistique-send-swift",
    ),
    path(
        "<int:pk>/confirm_payment_receipt/",
        LogisticsPaymentReceiptConfirmView.as_view(),
        name="logistique-confirm-payment-receipt",
    ),
]
